// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/tag_service/tag_service.proto (package ablibrary.services.tag_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DetailsRequest, DetailsResponse, ListRequest, ListResponse } from "./tag_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.tag_service.TagService
 */
export const TagService = {
  typeName: "ablibrary.services.tag_service.TagService",
  methods: {
    /**
     * @generated from rpc ablibrary.services.tag_service.TagService.List
     */
    list: {
      name: "List",
      I: ListRequest,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.tag_service.TagService.Details
     */
    details: {
      name: "Details",
      I: DetailsRequest,
      O: DetailsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

