// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/file_transfer_service/file_transfer_service.proto (package ablibrary.services.file_transfer_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Error } from "../../types/common_pb";
import { Book } from "../../types/book_pb";

/**
 * @generated from enum ablibrary.services.file_transfer_service.TransferType
 */
export enum TransferType {
  /**
   * @generated from enum value: TRANSFER_TYPE_DOWNLOAD_FILE = 0;
   */
  DOWNLOAD_FILE = 0,

  /**
   * @generated from enum value: TRANSFER_TYPE_UPLOAD_FILE = 1;
   */
  UPLOAD_FILE = 1,

  /**
   * @generated from enum value: TRANSFER_TYPE_DOWNLOAD_BOOK = 2;
   */
  DOWNLOAD_BOOK = 2,

  /**
   * @generated from enum value: TRANSFER_TYPE_UPLOAD_BOOK = 3;
   */
  UPLOAD_BOOK = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(TransferType)
proto3.util.setEnumType(TransferType, "ablibrary.services.file_transfer_service.TransferType", [
  { no: 0, name: "TRANSFER_TYPE_DOWNLOAD_FILE" },
  { no: 1, name: "TRANSFER_TYPE_UPLOAD_FILE" },
  { no: 2, name: "TRANSFER_TYPE_DOWNLOAD_BOOK" },
  { no: 3, name: "TRANSFER_TYPE_UPLOAD_BOOK" },
]);

/**
 * @generated from enum ablibrary.services.file_transfer_service.TransferState
 */
export enum TransferState {
  /**
   * @generated from enum value: TRANSFER_STATE_QUEUED = 0;
   */
  QUEUED = 0,

  /**
   * @generated from enum value: TRANSFER_STATE_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: TRANSFER_STATE_FINISHED = 2;
   */
  FINISHED = 2,

  /**
   * @generated from enum value: TRANSFER_STATE_ERROR = 3;
   */
  ERROR = 3,

  /**
   * @generated from enum value: TRANSFER_STATE_STOPPED = 4;
   */
  STOPPED = 4,

  /**
   * @generated from enum value: TRANSFER_STATE_CANCELED = 5;
   */
  CANCELED = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(TransferState)
proto3.util.setEnumType(TransferState, "ablibrary.services.file_transfer_service.TransferState", [
  { no: 0, name: "TRANSFER_STATE_QUEUED" },
  { no: 1, name: "TRANSFER_STATE_ACTIVE" },
  { no: 2, name: "TRANSFER_STATE_FINISHED" },
  { no: 3, name: "TRANSFER_STATE_ERROR" },
  { no: 4, name: "TRANSFER_STATE_STOPPED" },
  { no: 5, name: "TRANSFER_STATE_CANCELED" },
]);

/**
 * @generated from enum ablibrary.services.file_transfer_service.QueueState
 */
export enum QueueState {
  /**
   * @generated from enum value: QUEUE_STATE_ACTIVE = 0;
   */
  ACTIVE = 0,

  /**
   * @generated from enum value: QUEUE_STATE_PAUSED = 1;
   */
  PAUSED = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(QueueState)
proto3.util.setEnumType(QueueState, "ablibrary.services.file_transfer_service.QueueState", [
  { no: 0, name: "QUEUE_STATE_ACTIVE" },
  { no: 1, name: "QUEUE_STATE_PAUSED" },
]);

/**
 * @generated from message ablibrary.services.file_transfer_service.QueueRequest
 */
export class QueueRequest extends Message<QueueRequest> {
  constructor(data?: PartialMessage<QueueRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.QueueRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueueRequest {
    return new QueueRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueueRequest {
    return new QueueRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueueRequest {
    return new QueueRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueueRequest | PlainMessage<QueueRequest> | undefined, b: QueueRequest | PlainMessage<QueueRequest> | undefined): boolean {
    return proto3.util.equals(QueueRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.QueueResponse
 */
export class QueueResponse extends Message<QueueResponse> {
  /**
   * In the initial response, the transfers field will contain all transfers in the queue.
   * In subsequent responses, it will only include transfers whose statuses have been updated.
   * It is the client’s responsibility to manage and synchronize its local state accordingly.
   *
   * @generated from field: repeated ablibrary.services.file_transfer_service.Transfer transfers = 1;
   */
  transfers: Transfer[] = [];

  /**
   * @generated from field: ablibrary.services.file_transfer_service.QueueState state = 2;
   */
  state = QueueState.ACTIVE;

  constructor(data?: PartialMessage<QueueResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.QueueResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transfers", kind: "message", T: Transfer, repeated: true },
    { no: 2, name: "state", kind: "enum", T: proto3.getEnumType(QueueState) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueueResponse {
    return new QueueResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueueResponse {
    return new QueueResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueueResponse {
    return new QueueResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueueResponse | PlainMessage<QueueResponse> | undefined, b: QueueResponse | PlainMessage<QueueResponse> | undefined): boolean {
    return proto3.util.equals(QueueResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.PauseQueueRequest
 */
export class PauseQueueRequest extends Message<PauseQueueRequest> {
  constructor(data?: PartialMessage<PauseQueueRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.PauseQueueRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PauseQueueRequest {
    return new PauseQueueRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PauseQueueRequest {
    return new PauseQueueRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PauseQueueRequest {
    return new PauseQueueRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PauseQueueRequest | PlainMessage<PauseQueueRequest> | undefined, b: PauseQueueRequest | PlainMessage<PauseQueueRequest> | undefined): boolean {
    return proto3.util.equals(PauseQueueRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.PauseQueueResponse
 */
export class PauseQueueResponse extends Message<PauseQueueResponse> {
  constructor(data?: PartialMessage<PauseQueueResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.PauseQueueResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PauseQueueResponse {
    return new PauseQueueResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PauseQueueResponse {
    return new PauseQueueResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PauseQueueResponse {
    return new PauseQueueResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PauseQueueResponse | PlainMessage<PauseQueueResponse> | undefined, b: PauseQueueResponse | PlainMessage<PauseQueueResponse> | undefined): boolean {
    return proto3.util.equals(PauseQueueResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.ResumeQueueRequest
 */
export class ResumeQueueRequest extends Message<ResumeQueueRequest> {
  constructor(data?: PartialMessage<ResumeQueueRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.ResumeQueueRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResumeQueueRequest {
    return new ResumeQueueRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResumeQueueRequest {
    return new ResumeQueueRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResumeQueueRequest {
    return new ResumeQueueRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ResumeQueueRequest | PlainMessage<ResumeQueueRequest> | undefined, b: ResumeQueueRequest | PlainMessage<ResumeQueueRequest> | undefined): boolean {
    return proto3.util.equals(ResumeQueueRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.ResumeQueueResponse
 */
export class ResumeQueueResponse extends Message<ResumeQueueResponse> {
  constructor(data?: PartialMessage<ResumeQueueResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.ResumeQueueResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResumeQueueResponse {
    return new ResumeQueueResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResumeQueueResponse {
    return new ResumeQueueResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResumeQueueResponse {
    return new ResumeQueueResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ResumeQueueResponse | PlainMessage<ResumeQueueResponse> | undefined, b: ResumeQueueResponse | PlainMessage<ResumeQueueResponse> | undefined): boolean {
    return proto3.util.equals(ResumeQueueResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.DownloadBookRequest
 */
export class DownloadBookRequest extends Message<DownloadBookRequest> {
  /**
   * @generated from field: repeated string book_ids = 1;
   */
  bookIds: string[] = [];

  constructor(data?: PartialMessage<DownloadBookRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.DownloadBookRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "book_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadBookRequest {
    return new DownloadBookRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadBookRequest {
    return new DownloadBookRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadBookRequest {
    return new DownloadBookRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DownloadBookRequest | PlainMessage<DownloadBookRequest> | undefined, b: DownloadBookRequest | PlainMessage<DownloadBookRequest> | undefined): boolean {
    return proto3.util.equals(DownloadBookRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.DownloadBookResponse
 */
export class DownloadBookResponse extends Message<DownloadBookResponse> {
  /**
   * map of book_id to transfer_id
   *
   * @generated from field: map<string, string> book_transfer_ids = 1;
   */
  bookTransferIds: { [key: string]: string } = {};

  constructor(data?: PartialMessage<DownloadBookResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.DownloadBookResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "book_transfer_ids", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadBookResponse {
    return new DownloadBookResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadBookResponse {
    return new DownloadBookResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadBookResponse {
    return new DownloadBookResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DownloadBookResponse | PlainMessage<DownloadBookResponse> | undefined, b: DownloadBookResponse | PlainMessage<DownloadBookResponse> | undefined): boolean {
    return proto3.util.equals(DownloadBookResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.DownloadFileRequest
 */
export class DownloadFileRequest extends Message<DownloadFileRequest> {
  /**
   * @generated from field: repeated string file_ids = 1;
   */
  fileIds: string[] = [];

  constructor(data?: PartialMessage<DownloadFileRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.DownloadFileRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "file_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadFileRequest {
    return new DownloadFileRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadFileRequest {
    return new DownloadFileRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadFileRequest {
    return new DownloadFileRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DownloadFileRequest | PlainMessage<DownloadFileRequest> | undefined, b: DownloadFileRequest | PlainMessage<DownloadFileRequest> | undefined): boolean {
    return proto3.util.equals(DownloadFileRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.DownloadFileResponse
 */
export class DownloadFileResponse extends Message<DownloadFileResponse> {
  /**
   * map of file_id to transfer_id
   *
   * @generated from field: map<string, string> file_transfer_ids = 1;
   */
  fileTransferIds: { [key: string]: string } = {};

  constructor(data?: PartialMessage<DownloadFileResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.DownloadFileResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "file_transfer_ids", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadFileResponse {
    return new DownloadFileResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadFileResponse {
    return new DownloadFileResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadFileResponse {
    return new DownloadFileResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DownloadFileResponse | PlainMessage<DownloadFileResponse> | undefined, b: DownloadFileResponse | PlainMessage<DownloadFileResponse> | undefined): boolean {
    return proto3.util.equals(DownloadFileResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.UploadBookRequest
 */
export class UploadBookRequest extends Message<UploadBookRequest> {
  constructor(data?: PartialMessage<UploadBookRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.UploadBookRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadBookRequest {
    return new UploadBookRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadBookRequest {
    return new UploadBookRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadBookRequest {
    return new UploadBookRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UploadBookRequest | PlainMessage<UploadBookRequest> | undefined, b: UploadBookRequest | PlainMessage<UploadBookRequest> | undefined): boolean {
    return proto3.util.equals(UploadBookRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.UploadBookResponse
 */
export class UploadBookResponse extends Message<UploadBookResponse> {
  constructor(data?: PartialMessage<UploadBookResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.UploadBookResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadBookResponse {
    return new UploadBookResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadBookResponse {
    return new UploadBookResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadBookResponse {
    return new UploadBookResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UploadBookResponse | PlainMessage<UploadBookResponse> | undefined, b: UploadBookResponse | PlainMessage<UploadBookResponse> | undefined): boolean {
    return proto3.util.equals(UploadBookResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.UploadFileRequest
 */
export class UploadFileRequest extends Message<UploadFileRequest> {
  constructor(data?: PartialMessage<UploadFileRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.UploadFileRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadFileRequest {
    return new UploadFileRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadFileRequest {
    return new UploadFileRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadFileRequest {
    return new UploadFileRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UploadFileRequest | PlainMessage<UploadFileRequest> | undefined, b: UploadFileRequest | PlainMessage<UploadFileRequest> | undefined): boolean {
    return proto3.util.equals(UploadFileRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.UploadFileResponse
 */
export class UploadFileResponse extends Message<UploadFileResponse> {
  constructor(data?: PartialMessage<UploadFileResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.UploadFileResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadFileResponse {
    return new UploadFileResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadFileResponse {
    return new UploadFileResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadFileResponse {
    return new UploadFileResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UploadFileResponse | PlainMessage<UploadFileResponse> | undefined, b: UploadFileResponse | PlainMessage<UploadFileResponse> | undefined): boolean {
    return proto3.util.equals(UploadFileResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.StopRequest
 */
export class StopRequest extends Message<StopRequest> {
  /**
   * @generated from field: repeated string transfer_ids = 1;
   */
  transferIds: string[] = [];

  constructor(data?: PartialMessage<StopRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.StopRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transfer_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopRequest {
    return new StopRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopRequest {
    return new StopRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopRequest {
    return new StopRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StopRequest | PlainMessage<StopRequest> | undefined, b: StopRequest | PlainMessage<StopRequest> | undefined): boolean {
    return proto3.util.equals(StopRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.StopResponse
 */
export class StopResponse extends Message<StopResponse> {
  constructor(data?: PartialMessage<StopResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.StopResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopResponse {
    return new StopResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopResponse {
    return new StopResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopResponse {
    return new StopResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StopResponse | PlainMessage<StopResponse> | undefined, b: StopResponse | PlainMessage<StopResponse> | undefined): boolean {
    return proto3.util.equals(StopResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.StopAllRequest
 */
export class StopAllRequest extends Message<StopAllRequest> {
  constructor(data?: PartialMessage<StopAllRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.StopAllRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopAllRequest {
    return new StopAllRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopAllRequest {
    return new StopAllRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopAllRequest {
    return new StopAllRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StopAllRequest | PlainMessage<StopAllRequest> | undefined, b: StopAllRequest | PlainMessage<StopAllRequest> | undefined): boolean {
    return proto3.util.equals(StopAllRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.StopAllResponse
 */
export class StopAllResponse extends Message<StopAllResponse> {
  constructor(data?: PartialMessage<StopAllResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.StopAllResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopAllResponse {
    return new StopAllResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopAllResponse {
    return new StopAllResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopAllResponse {
    return new StopAllResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StopAllResponse | PlainMessage<StopAllResponse> | undefined, b: StopAllResponse | PlainMessage<StopAllResponse> | undefined): boolean {
    return proto3.util.equals(StopAllResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.StartRequest
 */
export class StartRequest extends Message<StartRequest> {
  /**
   * @generated from field: repeated string transfer_ids = 1;
   */
  transferIds: string[] = [];

  constructor(data?: PartialMessage<StartRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.StartRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transfer_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartRequest {
    return new StartRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartRequest {
    return new StartRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartRequest {
    return new StartRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StartRequest | PlainMessage<StartRequest> | undefined, b: StartRequest | PlainMessage<StartRequest> | undefined): boolean {
    return proto3.util.equals(StartRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.StartResponse
 */
export class StartResponse extends Message<StartResponse> {
  constructor(data?: PartialMessage<StartResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.StartResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartResponse {
    return new StartResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartResponse {
    return new StartResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartResponse {
    return new StartResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StartResponse | PlainMessage<StartResponse> | undefined, b: StartResponse | PlainMessage<StartResponse> | undefined): boolean {
    return proto3.util.equals(StartResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.StartAllRequest
 */
export class StartAllRequest extends Message<StartAllRequest> {
  constructor(data?: PartialMessage<StartAllRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.StartAllRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartAllRequest {
    return new StartAllRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartAllRequest {
    return new StartAllRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartAllRequest {
    return new StartAllRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StartAllRequest | PlainMessage<StartAllRequest> | undefined, b: StartAllRequest | PlainMessage<StartAllRequest> | undefined): boolean {
    return proto3.util.equals(StartAllRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.StartAllResponse
 */
export class StartAllResponse extends Message<StartAllResponse> {
  constructor(data?: PartialMessage<StartAllResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.StartAllResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartAllResponse {
    return new StartAllResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartAllResponse {
    return new StartAllResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartAllResponse {
    return new StartAllResponse().fromJsonString(jsonString, options);
  }

  static equals(a: StartAllResponse | PlainMessage<StartAllResponse> | undefined, b: StartAllResponse | PlainMessage<StartAllResponse> | undefined): boolean {
    return proto3.util.equals(StartAllResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.CancellRequest
 */
export class CancellRequest extends Message<CancellRequest> {
  /**
   * @generated from field: repeated string transfer_ids = 1;
   */
  transferIds: string[] = [];

  constructor(data?: PartialMessage<CancellRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.CancellRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transfer_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancellRequest {
    return new CancellRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancellRequest {
    return new CancellRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancellRequest {
    return new CancellRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancellRequest | PlainMessage<CancellRequest> | undefined, b: CancellRequest | PlainMessage<CancellRequest> | undefined): boolean {
    return proto3.util.equals(CancellRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.CancellResponse
 */
export class CancellResponse extends Message<CancellResponse> {
  constructor(data?: PartialMessage<CancellResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.CancellResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancellResponse {
    return new CancellResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancellResponse {
    return new CancellResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancellResponse {
    return new CancellResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancellResponse | PlainMessage<CancellResponse> | undefined, b: CancellResponse | PlainMessage<CancellResponse> | undefined): boolean {
    return proto3.util.equals(CancellResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.CancellAllRequest
 */
export class CancellAllRequest extends Message<CancellAllRequest> {
  constructor(data?: PartialMessage<CancellAllRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.CancellAllRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancellAllRequest {
    return new CancellAllRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancellAllRequest {
    return new CancellAllRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancellAllRequest {
    return new CancellAllRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancellAllRequest | PlainMessage<CancellAllRequest> | undefined, b: CancellAllRequest | PlainMessage<CancellAllRequest> | undefined): boolean {
    return proto3.util.equals(CancellAllRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.CancellAllResponse
 */
export class CancellAllResponse extends Message<CancellAllResponse> {
  constructor(data?: PartialMessage<CancellAllResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.CancellAllResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancellAllResponse {
    return new CancellAllResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancellAllResponse {
    return new CancellAllResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancellAllResponse {
    return new CancellAllResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancellAllResponse | PlainMessage<CancellAllResponse> | undefined, b: CancellAllResponse | PlainMessage<CancellAllResponse> | undefined): boolean {
    return proto3.util.equals(CancellAllResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.GetSettingsRequest
 */
export class GetSettingsRequest extends Message<GetSettingsRequest> {
  constructor(data?: PartialMessage<GetSettingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.GetSettingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSettingsRequest {
    return new GetSettingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSettingsRequest {
    return new GetSettingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSettingsRequest {
    return new GetSettingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSettingsRequest | PlainMessage<GetSettingsRequest> | undefined, b: GetSettingsRequest | PlainMessage<GetSettingsRequest> | undefined): boolean {
    return proto3.util.equals(GetSettingsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.GetSettingsResponse
 */
export class GetSettingsResponse extends Message<GetSettingsResponse> {
  /**
   * @generated from field: ablibrary.services.file_transfer_service.Settings settings = 1;
   */
  settings?: Settings;

  constructor(data?: PartialMessage<GetSettingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.GetSettingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "settings", kind: "message", T: Settings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSettingsResponse {
    return new GetSettingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSettingsResponse {
    return new GetSettingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSettingsResponse {
    return new GetSettingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetSettingsResponse | PlainMessage<GetSettingsResponse> | undefined, b: GetSettingsResponse | PlainMessage<GetSettingsResponse> | undefined): boolean {
    return proto3.util.equals(GetSettingsResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.SetSettingsRequest
 */
export class SetSettingsRequest extends Message<SetSettingsRequest> {
  /**
   * @generated from field: ablibrary.services.file_transfer_service.Settings settings = 1;
   */
  settings?: Settings;

  constructor(data?: PartialMessage<SetSettingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.SetSettingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "settings", kind: "message", T: Settings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSettingsRequest {
    return new SetSettingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSettingsRequest {
    return new SetSettingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSettingsRequest {
    return new SetSettingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetSettingsRequest | PlainMessage<SetSettingsRequest> | undefined, b: SetSettingsRequest | PlainMessage<SetSettingsRequest> | undefined): boolean {
    return proto3.util.equals(SetSettingsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.SetSettingsResponse
 */
export class SetSettingsResponse extends Message<SetSettingsResponse> {
  constructor(data?: PartialMessage<SetSettingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.SetSettingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSettingsResponse {
    return new SetSettingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSettingsResponse {
    return new SetSettingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSettingsResponse {
    return new SetSettingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SetSettingsResponse | PlainMessage<SetSettingsResponse> | undefined, b: SetSettingsResponse | PlainMessage<SetSettingsResponse> | undefined): boolean {
    return proto3.util.equals(SetSettingsResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.Transfer
 */
export class Transfer extends Message<Transfer> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: optional string book_id = 2;
   */
  bookId?: string;

  /**
   * @generated from field: optional string file_id = 3;
   */
  fileId?: string;

  /**
   * @generated from field: string title = 4;
   */
  title = "";

  /**
   * @generated from field: ablibrary.services.file_transfer_service.TransferType type = 5;
   */
  type = TransferType.DOWNLOAD_FILE;

  /**
   * @generated from field: ablibrary.services.file_transfer_service.TransferState status = 6;
   */
  status = TransferState.QUEUED;

  /**
   * a number between 0.00 and 100.00
   *
   * @generated from field: float progress = 7;
   */
  progress = 0;

  /**
   * @generated from field: int64 bytes_total = 8;
   */
  bytesTotal = protoInt64.zero;

  /**
   * @generated from field: int64 bytes_transferred = 9;
   */
  bytesTransferred = protoInt64.zero;

  /**
   * @generated from field: int64 bytes_per_second = 10;
   */
  bytesPerSecond = protoInt64.zero;

  /**
   * @generated from field: ablibrary.types.Error error = 11;
   */
  error?: Error;

  /**
   * address of the source file.
   *
   * @generated from field: optional string src_url = 12;
   */
  srcUrl?: string;

  /**
   * address of the destination file.
   *
   * @generated from field: optional string dest_url = 13;
   */
  destUrl?: string;

  /**
   * @generated from field: optional ablibrary.types.Book book = 14;
   */
  book?: Book;

  constructor(data?: PartialMessage<Transfer>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.Transfer";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "book_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "file_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "type", kind: "enum", T: proto3.getEnumType(TransferType) },
    { no: 6, name: "status", kind: "enum", T: proto3.getEnumType(TransferState) },
    { no: 7, name: "progress", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 8, name: "bytes_total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "bytes_transferred", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "bytes_per_second", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 11, name: "error", kind: "message", T: Error },
    { no: 12, name: "src_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 13, name: "dest_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 14, name: "book", kind: "message", T: Book, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transfer {
    return new Transfer().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transfer {
    return new Transfer().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transfer {
    return new Transfer().fromJsonString(jsonString, options);
  }

  static equals(a: Transfer | PlainMessage<Transfer> | undefined, b: Transfer | PlainMessage<Transfer> | undefined): boolean {
    return proto3.util.equals(Transfer, a, b);
  }
}

/**
 * @generated from message ablibrary.services.file_transfer_service.Settings
 */
export class Settings extends Message<Settings> {
  /**
   * @generated from field: int32 max_concurrent_transfers = 1;
   */
  maxConcurrentTransfers = 0;

  /**
   * @generated from field: int32 max_retries = 2;
   */
  maxRetries = 0;

  /**
   * @generated from field: float retry_backoff_factor = 3;
   */
  retryBackoffFactor = 0;

  /**
   * @generated from field: string storage_dir = 4;
   */
  storageDir = "";

  /**
   * @generated from field: google.protobuf.Duration initial_retry_delay = 5;
   */
  initialRetryDelay?: Duration;

  /**
   * @generated from field: google.protobuf.Duration queue_stream_interval = 6;
   */
  queueStreamInterval?: Duration;

  /**
   * @generated from field: google.protobuf.Duration transfer_update_interval = 7;
   */
  transferUpdateInterval?: Duration;

  /**
   * @generated from field: google.protobuf.Duration transfer_update_send_timeout = 8;
   */
  transferUpdateSendTimeout?: Duration;

  constructor(data?: PartialMessage<Settings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.file_transfer_service.Settings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "max_concurrent_transfers", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "max_retries", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "retry_backoff_factor", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 4, name: "storage_dir", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "initial_retry_delay", kind: "message", T: Duration },
    { no: 6, name: "queue_stream_interval", kind: "message", T: Duration },
    { no: 7, name: "transfer_update_interval", kind: "message", T: Duration },
    { no: 8, name: "transfer_update_send_timeout", kind: "message", T: Duration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Settings {
    return new Settings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Settings {
    return new Settings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Settings {
    return new Settings().fromJsonString(jsonString, options);
  }

  static equals(a: Settings | PlainMessage<Settings> | undefined, b: Settings | PlainMessage<Settings> | undefined): boolean {
    return proto3.util.equals(Settings, a, b);
  }
}

