// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/file_transfer_service/file_transfer_service.proto (package ablibrary.services.file_transfer_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancellAllRequest, CancellAllResponse, CancellRequest, CancellResponse, DownloadBookRequest, DownloadBookResponse, DownloadFileRequest, DownloadFileResponse, GetSettingsRequest, GetSettingsResponse, PauseQueueRequest, PauseQueueResponse, QueueRequest, QueueResponse, ResumeQueueRequest, ResumeQueueResponse, SetSettingsRequest, SetSettingsResponse, StartAllRequest, StartAllResponse, StartRequest, StartResponse, StopAllRequest, StopAllResponse, StopRequest, StopResponse, UploadBookRequest, UploadBookResponse, UploadFileRequest, UploadFileResponse } from "./file_transfer_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.file_transfer_service.FileTransferService
 */
export declare const FileTransferService: {
  readonly typeName: "ablibrary.services.file_transfer_service.FileTransferService",
  readonly methods: {
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.Queue
     */
    readonly queue: {
      readonly name: "Queue",
      readonly I: typeof QueueRequest,
      readonly O: typeof QueueResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.PauseQueue
     */
    readonly pauseQueue: {
      readonly name: "PauseQueue",
      readonly I: typeof PauseQueueRequest,
      readonly O: typeof PauseQueueResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.ResumeQueue
     */
    readonly resumeQueue: {
      readonly name: "ResumeQueue",
      readonly I: typeof ResumeQueueRequest,
      readonly O: typeof ResumeQueueResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.DownloadBook
     */
    readonly downloadBook: {
      readonly name: "DownloadBook",
      readonly I: typeof DownloadBookRequest,
      readonly O: typeof DownloadBookResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.UploadBook
     */
    readonly uploadBook: {
      readonly name: "UploadBook",
      readonly I: typeof UploadBookRequest,
      readonly O: typeof UploadBookResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.DownloadFile
     */
    readonly downloadFile: {
      readonly name: "DownloadFile",
      readonly I: typeof DownloadFileRequest,
      readonly O: typeof DownloadFileResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.UploadFile
     */
    readonly uploadFile: {
      readonly name: "UploadFile",
      readonly I: typeof UploadFileRequest,
      readonly O: typeof UploadFileResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.Stop
     */
    readonly stop: {
      readonly name: "Stop",
      readonly I: typeof StopRequest,
      readonly O: typeof StopResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.StopAll
     */
    readonly stopAll: {
      readonly name: "StopAll",
      readonly I: typeof StopAllRequest,
      readonly O: typeof StopAllResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.Start
     */
    readonly start: {
      readonly name: "Start",
      readonly I: typeof StartRequest,
      readonly O: typeof StartResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.StartAll
     */
    readonly startAll: {
      readonly name: "StartAll",
      readonly I: typeof StartAllRequest,
      readonly O: typeof StartAllResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.Cancell
     */
    readonly cancell: {
      readonly name: "Cancell",
      readonly I: typeof CancellRequest,
      readonly O: typeof CancellResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.CancellAll
     */
    readonly cancellAll: {
      readonly name: "CancellAll",
      readonly I: typeof CancellAllRequest,
      readonly O: typeof CancellAllResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.GetSettings
     */
    readonly getSettings: {
      readonly name: "GetSettings",
      readonly I: typeof GetSettingsRequest,
      readonly O: typeof GetSettingsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.file_transfer_service.FileTransferService.SetSettings
     */
    readonly setSettings: {
      readonly name: "SetSettings",
      readonly I: typeof SetSettingsRequest,
      readonly O: typeof SetSettingsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

