// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/book_service/book_service.proto (package ablibrary.services.book_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { FieldMask } from "../../types/field_mask_pb";
import type { DateTimeRange, RelationPresenceFilter, SortDirection } from "../../types/common_pb";
import type { DataState } from "../../types/metadata_pb";
import type { Book, BookAttachmentContext } from "../../types/book_pb";
import type { Pagination } from "../../types/pagination_pb";
import type { PageContentRef } from "../../types/page_content_pb";
import type { Page } from "../../types/page_pb";

/**
 * @generated from enum ablibrary.services.book_service.HTMLContentOption
 */
export declare enum HTMLContentOption {
  /**
   * Standalone wraps HTML content in standard HTML document with DOCTYPE, html, head and body tags.
   *
   * @generated from enum value: HTML_CONTENT_OPTION_STANDALONE = 0;
   */
  HTML_CONTENT_OPTION_STANDALONE = 0,

  /**
   * With default styles adds a style tag with default styles to the resulting HTML.
   *
   * @generated from enum value: HTML_CONTENT_OPTION_WITH_DEFAULT_STYLES = 1;
   */
  HTML_CONTENT_OPTION_WITH_DEFAULT_STYLES = 1,
}

/**
 * @generated from message ablibrary.services.book_service.ListRequest
 */
export declare class ListRequest extends Message<ListRequest> {
  /**
   * If mask is not set, fields in the "basic" template will be returned.
   *
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: optional int32 page = 2;
   */
  page?: number;

  /**
   * @generated from field: optional int32 per_page = 3;
   */
  perPage?: number;

  /**
   * @generated from field: optional ablibrary.services.book_service.ListRequest.Sort sort_by = 4;
   */
  sortBy?: ListRequest_Sort;

  /**
   * @generated from field: optional ablibrary.types.SortDirection sort_dir = 5;
   */
  sortDir?: SortDirection;

  /**
   * @generated from field: optional string query = 6;
   */
  query?: string;

  /**
   * @generated from field: repeated ablibrary.services.book_service.ListRequest.ContributorFilter contributors = 7;
   */
  contributors: ListRequest_ContributorFilter[];

  /**
   * @generated from field: repeated string categories = 8;
   */
  categories: string[];

  /**
   * @generated from field: repeated ablibrary.services.book_service.ListRequest.PublisherFilter publishers = 9;
   */
  publishers: ListRequest_PublisherFilter[];

  /**
   * @generated from field: repeated ablibrary.services.book_service.ListRequest.TagFilter tags = 10;
   */
  tags: ListRequest_TagFilter[];

  /**
   * @generated from field: optional bool is_downloaded = 11;
   */
  isDownloaded?: boolean;

  /**
   * @generated from field: repeated string labels = 12;
   */
  labels: string[];

  /**
   * @generated from field: repeated string languages = 13;
   */
  languages: string[];

  /**
   * @generated from field: repeated ablibrary.services.book_service.ListRequest.AttachmentFilter attachments = 14;
   */
  attachments: ListRequest_AttachmentFilter[];

  /**
   * @generated from field: repeated ablibrary.types.DataState status = 15;
   */
  status: DataState[];

  /**
   * @generated from field: optional string title = 16;
   */
  title?: string;

  /**
   * @generated from field: repeated string book_ids = 17;
   */
  bookIds: string[];

  constructor(data?: PartialMessage<ListRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest;

  static equals(a: ListRequest | PlainMessage<ListRequest> | undefined, b: ListRequest | PlainMessage<ListRequest> | undefined): boolean;
}

/**
 * @generated from enum ablibrary.services.book_service.ListRequest.Sort
 */
export declare enum ListRequest_Sort {
  /**
   * @generated from enum value: SORT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SORT_TITLE = 1;
   */
  TITLE = 1,

  /**
   * @generated from enum value: SORT_CONTRIBUTOR_NAME = 2;
   */
  CONTRIBUTOR_NAME = 2,

  /**
   * @generated from enum value: SORT_CONTRIBUTOR_DIED_AT = 3;
   */
  CONTRIBUTOR_DIED_AT = 3,

  /**
   * @generated from enum value: SORT_PAGE_COUNT = 4;
   */
  PAGE_COUNT = 4,

  /**
   * @generated from enum value: SORT_PUBLISHER = 5;
   */
  PUBLISHER = 5,

  /**
   * @generated from enum value: SORT_CREATED_AT = 6;
   */
  CREATED_AT = 6,

  /**
   * @generated from enum value: SORT_UPDATED_AT = 7;
   */
  UPDATED_AT = 7,
}

/**
 * @generated from message ablibrary.services.book_service.ListRequest.AttachmentFilter
 */
export declare class ListRequest_AttachmentFilter extends Message<ListRequest_AttachmentFilter> {
  /**
   * @generated from field: ablibrary.types.BookAttachmentContext context = 1;
   */
  context: BookAttachmentContext;

  /**
   * @generated from field: ablibrary.types.RelationPresenceFilter filter = 2;
   */
  filter: RelationPresenceFilter;

  constructor(data?: PartialMessage<ListRequest_AttachmentFilter>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest.AttachmentFilter";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_AttachmentFilter;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_AttachmentFilter;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_AttachmentFilter;

  static equals(a: ListRequest_AttachmentFilter | PlainMessage<ListRequest_AttachmentFilter> | undefined, b: ListRequest_AttachmentFilter | PlainMessage<ListRequest_AttachmentFilter> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.ListRequest.ContributorFilter
 */
export declare class ListRequest_ContributorFilter extends Message<ListRequest_ContributorFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string role = 3;
   */
  role?: string;

  /**
   * @generated from field: optional ablibrary.types.DateTimeRange died = 4;
   */
  died?: DateTimeRange;

  constructor(data?: PartialMessage<ListRequest_ContributorFilter>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest.ContributorFilter";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_ContributorFilter;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_ContributorFilter;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_ContributorFilter;

  static equals(a: ListRequest_ContributorFilter | PlainMessage<ListRequest_ContributorFilter> | undefined, b: ListRequest_ContributorFilter | PlainMessage<ListRequest_ContributorFilter> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.ListRequest.PublisherFilter
 */
export declare class ListRequest_PublisherFilter extends Message<ListRequest_PublisherFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  constructor(data?: PartialMessage<ListRequest_PublisherFilter>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest.PublisherFilter";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_PublisherFilter;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_PublisherFilter;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_PublisherFilter;

  static equals(a: ListRequest_PublisherFilter | PlainMessage<ListRequest_PublisherFilter> | undefined, b: ListRequest_PublisherFilter | PlainMessage<ListRequest_PublisherFilter> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.ListRequest.TagFilter
 */
export declare class ListRequest_TagFilter extends Message<ListRequest_TagFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  constructor(data?: PartialMessage<ListRequest_TagFilter>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest.TagFilter";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_TagFilter;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_TagFilter;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_TagFilter;

  static equals(a: ListRequest_TagFilter | PlainMessage<ListRequest_TagFilter> | undefined, b: ListRequest_TagFilter | PlainMessage<ListRequest_TagFilter> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.ListResponse
 */
export declare class ListResponse extends Message<ListResponse> {
  /**
   * @generated from field: repeated ablibrary.types.Book books = 1;
   */
  books: Book[];

  /**
   * @generated from field: ablibrary.types.Pagination pagination = 2;
   */
  pagination?: Pagination;

  constructor(data?: PartialMessage<ListResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.ListResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponse;

  static equals(a: ListResponse | PlainMessage<ListResponse> | undefined, b: ListResponse | PlainMessage<ListResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.DetailsRequest
 */
export declare class DetailsRequest extends Message<DetailsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  constructor(data?: PartialMessage<DetailsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.DetailsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsRequest;

  static equals(a: DetailsRequest | PlainMessage<DetailsRequest> | undefined, b: DetailsRequest | PlainMessage<DetailsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.DetailsResponse
 */
export declare class DetailsResponse extends Message<DetailsResponse> {
  /**
   * @generated from field: ablibrary.types.Book book = 1;
   */
  book?: Book;

  constructor(data?: PartialMessage<DetailsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.DetailsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsResponse;

  static equals(a: DetailsResponse | PlainMessage<DetailsResponse> | undefined, b: DetailsResponse | PlainMessage<DetailsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.TableOfContentsRequest
 */
export declare class TableOfContentsRequest extends Message<TableOfContentsRequest> {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  constructor(data?: PartialMessage<TableOfContentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.TableOfContentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TableOfContentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TableOfContentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TableOfContentsRequest;

  static equals(a: TableOfContentsRequest | PlainMessage<TableOfContentsRequest> | undefined, b: TableOfContentsRequest | PlainMessage<TableOfContentsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.TableOfContentsResponse
 */
export declare class TableOfContentsResponse extends Message<TableOfContentsResponse> {
  /**
   * @generated from field: repeated ablibrary.types.PageContentRef items = 1;
   */
  items: PageContentRef[];

  constructor(data?: PartialMessage<TableOfContentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.TableOfContentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TableOfContentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TableOfContentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TableOfContentsResponse;

  static equals(a: TableOfContentsResponse | PlainMessage<TableOfContentsResponse> | undefined, b: TableOfContentsResponse | PlainMessage<TableOfContentsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.ContentsRequest
 */
export declare class ContentsRequest extends Message<ContentsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string book_id = 2;
   */
  bookId: string;

  /**
   * If page_numbers is not set, all pages are returned. If page_ids is set, this field will be ignored.
   *
   * @generated from field: repeated int32 page_numbers = 3;
   */
  pageNumbers: number[];

  /**
   * @generated from field: repeated string page_ids = 4;
   */
  pageIds: string[];

  constructor(data?: PartialMessage<ContentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.ContentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ContentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ContentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ContentsRequest;

  static equals(a: ContentsRequest | PlainMessage<ContentsRequest> | undefined, b: ContentsRequest | PlainMessage<ContentsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.ContentsResponse
 */
export declare class ContentsResponse extends Message<ContentsResponse> {
  /**
   * @generated from field: repeated ablibrary.types.Page pages = 1;
   */
  pages: Page[];

  constructor(data?: PartialMessage<ContentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.ContentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ContentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ContentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ContentsResponse;

  static equals(a: ContentsResponse | PlainMessage<ContentsResponse> | undefined, b: ContentsResponse | PlainMessage<ContentsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.HTMLContentsRequest
 */
export declare class HTMLContentsRequest extends Message<HTMLContentsRequest> {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * If page_numbers is not set, all pages are returned. If page_ids is set, this field will be ignored.
   *
   * @generated from field: repeated int32 page_numbers = 2;
   */
  pageNumbers: number[];

  /**
   * @generated from field: repeated string page_ids = 3;
   */
  pageIds: string[];

  /**
   * @generated from field: repeated ablibrary.services.book_service.HTMLContentOption options = 4;
   */
  options: HTMLContentOption[];

  constructor(data?: PartialMessage<HTMLContentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.HTMLContentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HTMLContentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HTMLContentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HTMLContentsRequest;

  static equals(a: HTMLContentsRequest | PlainMessage<HTMLContentsRequest> | undefined, b: HTMLContentsRequest | PlainMessage<HTMLContentsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.HTMLContentsResponse
 */
export declare class HTMLContentsResponse extends Message<HTMLContentsResponse> {
  /**
   * @generated from field: string data = 1;
   */
  data: string;

  constructor(data?: PartialMessage<HTMLContentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.HTMLContentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HTMLContentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HTMLContentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HTMLContentsResponse;

  static equals(a: HTMLContentsResponse | PlainMessage<HTMLContentsResponse> | undefined, b: HTMLContentsResponse | PlainMessage<HTMLContentsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.PDFContentsRequest
 */
export declare class PDFContentsRequest extends Message<PDFContentsRequest> {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * If page_numbers is not set, all pages are returned. If page_ids is set, this field will be ignored.
   *
   * @generated from field: repeated int32 page_numbers = 2;
   */
  pageNumbers: number[];

  /**
   * @generated from field: repeated string page_ids = 3;
   */
  pageIds: string[];

  constructor(data?: PartialMessage<PDFContentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.PDFContentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PDFContentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PDFContentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PDFContentsRequest;

  static equals(a: PDFContentsRequest | PlainMessage<PDFContentsRequest> | undefined, b: PDFContentsRequest | PlainMessage<PDFContentsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.PDFContentsResponse
 */
export declare class PDFContentsResponse extends Message<PDFContentsResponse> {
  constructor(data?: PartialMessage<PDFContentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.PDFContentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PDFContentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PDFContentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PDFContentsResponse;

  static equals(a: PDFContentsResponse | PlainMessage<PDFContentsResponse> | undefined, b: PDFContentsResponse | PlainMessage<PDFContentsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.FindRequest
 */
export declare class FindRequest extends Message<FindRequest> {
  constructor(data?: PartialMessage<FindRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.FindRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FindRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FindRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FindRequest;

  static equals(a: FindRequest | PlainMessage<FindRequest> | undefined, b: FindRequest | PlainMessage<FindRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.FindResponse
 */
export declare class FindResponse extends Message<FindResponse> {
  constructor(data?: PartialMessage<FindResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.FindResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FindResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FindResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FindResponse;

  static equals(a: FindResponse | PlainMessage<FindResponse> | undefined, b: FindResponse | PlainMessage<FindResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.CloseBookRequest
 */
export declare class CloseBookRequest extends Message<CloseBookRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string page_id = 2;
   */
  pageId?: string;

  constructor(data?: PartialMessage<CloseBookRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.CloseBookRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CloseBookRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CloseBookRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CloseBookRequest;

  static equals(a: CloseBookRequest | PlainMessage<CloseBookRequest> | undefined, b: CloseBookRequest | PlainMessage<CloseBookRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.CloseBookResponse
 */
export declare class CloseBookResponse extends Message<CloseBookResponse> {
  constructor(data?: PartialMessage<CloseBookResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.CloseBookResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CloseBookResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CloseBookResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CloseBookResponse;

  static equals(a: CloseBookResponse | PlainMessage<CloseBookResponse> | undefined, b: CloseBookResponse | PlainMessage<CloseBookResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.GetSettingsRequest
 */
export declare class GetSettingsRequest extends Message<GetSettingsRequest> {
  constructor(data?: PartialMessage<GetSettingsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.GetSettingsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSettingsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSettingsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSettingsRequest;

  static equals(a: GetSettingsRequest | PlainMessage<GetSettingsRequest> | undefined, b: GetSettingsRequest | PlainMessage<GetSettingsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.GetSettingsResponse
 */
export declare class GetSettingsResponse extends Message<GetSettingsResponse> {
  /**
   * @generated from field: ablibrary.services.book_service.Settings settings = 1;
   */
  settings?: Settings;

  constructor(data?: PartialMessage<GetSettingsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.GetSettingsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSettingsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSettingsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSettingsResponse;

  static equals(a: GetSettingsResponse | PlainMessage<GetSettingsResponse> | undefined, b: GetSettingsResponse | PlainMessage<GetSettingsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.SetSettingsRequest
 */
export declare class SetSettingsRequest extends Message<SetSettingsRequest> {
  /**
   * @generated from field: ablibrary.services.book_service.Settings settings = 1;
   */
  settings?: Settings;

  constructor(data?: PartialMessage<SetSettingsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.SetSettingsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSettingsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSettingsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSettingsRequest;

  static equals(a: SetSettingsRequest | PlainMessage<SetSettingsRequest> | undefined, b: SetSettingsRequest | PlainMessage<SetSettingsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.SetSettingsResponse
 */
export declare class SetSettingsResponse extends Message<SetSettingsResponse> {
  constructor(data?: PartialMessage<SetSettingsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.SetSettingsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSettingsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSettingsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSettingsResponse;

  static equals(a: SetSettingsResponse | PlainMessage<SetSettingsResponse> | undefined, b: SetSettingsResponse | PlainMessage<SetSettingsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.book_service.Settings
 */
export declare class Settings extends Message<Settings> {
  /**
   * @generated from field: string reader_font_family = 1;
   */
  readerFontFamily: string;

  /**
   * @generated from field: string reader_font_size = 2;
   */
  readerFontSize: string;

  /**
   * @generated from field: string reader_background_color = 3;
   */
  readerBackgroundColor: string;

  /**
   * @generated from field: string reader_font_color = 4;
   */
  readerFontColor: string;

  constructor(data?: PartialMessage<Settings>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.book_service.Settings";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Settings;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Settings;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Settings;

  static equals(a: Settings | PlainMessage<Settings> | undefined, b: Settings | PlainMessage<Settings> | undefined): boolean;
}

