// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/book_service/book_service.proto (package ablibrary.services.book_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { FieldMask } from "../../types/field_mask_pb";
import { DateTimeRange, RelationPresenceFilter, SortDirection } from "../../types/common_pb";
import { DataState } from "../../types/metadata_pb";
import { Book, BookAttachmentContext } from "../../types/book_pb";
import { Pagination } from "../../types/pagination_pb";
import { PageContentRef } from "../../types/page_content_pb";
import { Page } from "../../types/page_pb";

/**
 * @generated from enum ablibrary.services.book_service.HTMLContentOption
 */
export enum HTMLContentOption {
  /**
   * Standalone wraps HTML content in standard HTML document with DOCTYPE, html, head and body tags.
   *
   * @generated from enum value: HTML_CONTENT_OPTION_STANDALONE = 0;
   */
  HTML_CONTENT_OPTION_STANDALONE = 0,

  /**
   * With default styles adds a style tag with default styles to the resulting HTML.
   *
   * @generated from enum value: HTML_CONTENT_OPTION_WITH_DEFAULT_STYLES = 1;
   */
  HTML_CONTENT_OPTION_WITH_DEFAULT_STYLES = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(HTMLContentOption)
proto3.util.setEnumType(HTMLContentOption, "ablibrary.services.book_service.HTMLContentOption", [
  { no: 0, name: "HTML_CONTENT_OPTION_STANDALONE" },
  { no: 1, name: "HTML_CONTENT_OPTION_WITH_DEFAULT_STYLES" },
]);

/**
 * @generated from message ablibrary.services.book_service.ListRequest
 */
export class ListRequest extends Message<ListRequest> {
  /**
   * If mask is not set, fields in the "basic" template will be returned.
   *
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: optional int32 page = 2;
   */
  page?: number;

  /**
   * @generated from field: optional int32 per_page = 3;
   */
  perPage?: number;

  /**
   * @generated from field: optional ablibrary.services.book_service.ListRequest.Sort sort_by = 4;
   */
  sortBy?: ListRequest_Sort;

  /**
   * @generated from field: optional ablibrary.types.SortDirection sort_dir = 5;
   */
  sortDir?: SortDirection;

  /**
   * @generated from field: optional string query = 6;
   */
  query?: string;

  /**
   * @generated from field: repeated ablibrary.services.book_service.ListRequest.ContributorFilter contributors = 7;
   */
  contributors: ListRequest_ContributorFilter[] = [];

  /**
   * @generated from field: repeated string categories = 8;
   */
  categories: string[] = [];

  /**
   * @generated from field: repeated ablibrary.services.book_service.ListRequest.PublisherFilter publishers = 9;
   */
  publishers: ListRequest_PublisherFilter[] = [];

  /**
   * @generated from field: repeated ablibrary.services.book_service.ListRequest.TagFilter tags = 10;
   */
  tags: ListRequest_TagFilter[] = [];

  /**
   * @generated from field: optional bool is_downloaded = 11;
   */
  isDownloaded?: boolean;

  /**
   * @generated from field: repeated string labels = 12;
   */
  labels: string[] = [];

  /**
   * @generated from field: repeated string languages = 13;
   */
  languages: string[] = [];

  /**
   * @generated from field: repeated ablibrary.services.book_service.ListRequest.AttachmentFilter attachments = 14;
   */
  attachments: ListRequest_AttachmentFilter[] = [];

  /**
   * @generated from field: repeated ablibrary.types.DataState status = 15;
   */
  status: DataState[] = [];

  /**
   * @generated from field: optional string title = 16;
   */
  title?: string;

  /**
   * @generated from field: repeated string book_ids = 17;
   */
  bookIds: string[] = [];

  constructor(data?: PartialMessage<ListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mask", kind: "message", T: FieldMask, opt: true },
    { no: 2, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 3, name: "per_page", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 4, name: "sort_by", kind: "enum", T: proto3.getEnumType(ListRequest_Sort), opt: true },
    { no: 5, name: "sort_dir", kind: "enum", T: proto3.getEnumType(SortDirection), opt: true },
    { no: 6, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "contributors", kind: "message", T: ListRequest_ContributorFilter, repeated: true },
    { no: 8, name: "categories", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 9, name: "publishers", kind: "message", T: ListRequest_PublisherFilter, repeated: true },
    { no: 10, name: "tags", kind: "message", T: ListRequest_TagFilter, repeated: true },
    { no: 11, name: "is_downloaded", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 12, name: "labels", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 13, name: "languages", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 14, name: "attachments", kind: "message", T: ListRequest_AttachmentFilter, repeated: true },
    { no: 15, name: "status", kind: "enum", T: proto3.getEnumType(DataState), repeated: true },
    { no: 16, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 17, name: "book_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest {
    return new ListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest {
    return new ListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest {
    return new ListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest | PlainMessage<ListRequest> | undefined, b: ListRequest | PlainMessage<ListRequest> | undefined): boolean {
    return proto3.util.equals(ListRequest, a, b);
  }
}

/**
 * @generated from enum ablibrary.services.book_service.ListRequest.Sort
 */
export enum ListRequest_Sort {
  /**
   * @generated from enum value: SORT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SORT_TITLE = 1;
   */
  TITLE = 1,

  /**
   * @generated from enum value: SORT_CONTRIBUTOR_NAME = 2;
   */
  CONTRIBUTOR_NAME = 2,

  /**
   * @generated from enum value: SORT_CONTRIBUTOR_DIED_AT = 3;
   */
  CONTRIBUTOR_DIED_AT = 3,

  /**
   * @generated from enum value: SORT_PAGE_COUNT = 4;
   */
  PAGE_COUNT = 4,

  /**
   * @generated from enum value: SORT_PUBLISHER = 5;
   */
  PUBLISHER = 5,

  /**
   * @generated from enum value: SORT_CREATED_AT = 6;
   */
  CREATED_AT = 6,

  /**
   * @generated from enum value: SORT_UPDATED_AT = 7;
   */
  UPDATED_AT = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(ListRequest_Sort)
proto3.util.setEnumType(ListRequest_Sort, "ablibrary.services.book_service.ListRequest.Sort", [
  { no: 0, name: "SORT_UNSPECIFIED" },
  { no: 1, name: "SORT_TITLE" },
  { no: 2, name: "SORT_CONTRIBUTOR_NAME" },
  { no: 3, name: "SORT_CONTRIBUTOR_DIED_AT" },
  { no: 4, name: "SORT_PAGE_COUNT" },
  { no: 5, name: "SORT_PUBLISHER" },
  { no: 6, name: "SORT_CREATED_AT" },
  { no: 7, name: "SORT_UPDATED_AT" },
]);

/**
 * @generated from message ablibrary.services.book_service.ListRequest.AttachmentFilter
 */
export class ListRequest_AttachmentFilter extends Message<ListRequest_AttachmentFilter> {
  /**
   * @generated from field: ablibrary.types.BookAttachmentContext context = 1;
   */
  context = BookAttachmentContext.UNSPECIFIED;

  /**
   * @generated from field: ablibrary.types.RelationPresenceFilter filter = 2;
   */
  filter = RelationPresenceFilter.PRESENT;

  constructor(data?: PartialMessage<ListRequest_AttachmentFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest.AttachmentFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "context", kind: "enum", T: proto3.getEnumType(BookAttachmentContext) },
    { no: 2, name: "filter", kind: "enum", T: proto3.getEnumType(RelationPresenceFilter) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_AttachmentFilter {
    return new ListRequest_AttachmentFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_AttachmentFilter {
    return new ListRequest_AttachmentFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_AttachmentFilter {
    return new ListRequest_AttachmentFilter().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest_AttachmentFilter | PlainMessage<ListRequest_AttachmentFilter> | undefined, b: ListRequest_AttachmentFilter | PlainMessage<ListRequest_AttachmentFilter> | undefined): boolean {
    return proto3.util.equals(ListRequest_AttachmentFilter, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.ListRequest.ContributorFilter
 */
export class ListRequest_ContributorFilter extends Message<ListRequest_ContributorFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string role = 3;
   */
  role?: string;

  /**
   * @generated from field: optional ablibrary.types.DateTimeRange died = 4;
   */
  died?: DateTimeRange;

  constructor(data?: PartialMessage<ListRequest_ContributorFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest.ContributorFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "died", kind: "message", T: DateTimeRange, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_ContributorFilter {
    return new ListRequest_ContributorFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_ContributorFilter {
    return new ListRequest_ContributorFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_ContributorFilter {
    return new ListRequest_ContributorFilter().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest_ContributorFilter | PlainMessage<ListRequest_ContributorFilter> | undefined, b: ListRequest_ContributorFilter | PlainMessage<ListRequest_ContributorFilter> | undefined): boolean {
    return proto3.util.equals(ListRequest_ContributorFilter, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.ListRequest.PublisherFilter
 */
export class ListRequest_PublisherFilter extends Message<ListRequest_PublisherFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  constructor(data?: PartialMessage<ListRequest_PublisherFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest.PublisherFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_PublisherFilter {
    return new ListRequest_PublisherFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_PublisherFilter {
    return new ListRequest_PublisherFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_PublisherFilter {
    return new ListRequest_PublisherFilter().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest_PublisherFilter | PlainMessage<ListRequest_PublisherFilter> | undefined, b: ListRequest_PublisherFilter | PlainMessage<ListRequest_PublisherFilter> | undefined): boolean {
    return proto3.util.equals(ListRequest_PublisherFilter, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.ListRequest.TagFilter
 */
export class ListRequest_TagFilter extends Message<ListRequest_TagFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  constructor(data?: PartialMessage<ListRequest_TagFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.ListRequest.TagFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_TagFilter {
    return new ListRequest_TagFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_TagFilter {
    return new ListRequest_TagFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_TagFilter {
    return new ListRequest_TagFilter().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest_TagFilter | PlainMessage<ListRequest_TagFilter> | undefined, b: ListRequest_TagFilter | PlainMessage<ListRequest_TagFilter> | undefined): boolean {
    return proto3.util.equals(ListRequest_TagFilter, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.ListResponse
 */
export class ListResponse extends Message<ListResponse> {
  /**
   * @generated from field: repeated ablibrary.types.Book books = 1;
   */
  books: Book[] = [];

  /**
   * @generated from field: ablibrary.types.Pagination pagination = 2;
   */
  pagination?: Pagination;

  constructor(data?: PartialMessage<ListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.ListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "books", kind: "message", T: Book, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: Pagination },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponse {
    return new ListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponse {
    return new ListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponse {
    return new ListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListResponse | PlainMessage<ListResponse> | undefined, b: ListResponse | PlainMessage<ListResponse> | undefined): boolean {
    return proto3.util.equals(ListResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.DetailsRequest
 */
export class DetailsRequest extends Message<DetailsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string id = 2;
   */
  id = "";

  constructor(data?: PartialMessage<DetailsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.DetailsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mask", kind: "message", T: FieldMask, opt: true },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsRequest {
    return new DetailsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsRequest {
    return new DetailsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsRequest {
    return new DetailsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DetailsRequest | PlainMessage<DetailsRequest> | undefined, b: DetailsRequest | PlainMessage<DetailsRequest> | undefined): boolean {
    return proto3.util.equals(DetailsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.DetailsResponse
 */
export class DetailsResponse extends Message<DetailsResponse> {
  /**
   * @generated from field: ablibrary.types.Book book = 1;
   */
  book?: Book;

  constructor(data?: PartialMessage<DetailsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.DetailsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "book", kind: "message", T: Book },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsResponse {
    return new DetailsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsResponse {
    return new DetailsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsResponse {
    return new DetailsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DetailsResponse | PlainMessage<DetailsResponse> | undefined, b: DetailsResponse | PlainMessage<DetailsResponse> | undefined): boolean {
    return proto3.util.equals(DetailsResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.TableOfContentsRequest
 */
export class TableOfContentsRequest extends Message<TableOfContentsRequest> {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId = "";

  constructor(data?: PartialMessage<TableOfContentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.TableOfContentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "book_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TableOfContentsRequest {
    return new TableOfContentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TableOfContentsRequest {
    return new TableOfContentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TableOfContentsRequest {
    return new TableOfContentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: TableOfContentsRequest | PlainMessage<TableOfContentsRequest> | undefined, b: TableOfContentsRequest | PlainMessage<TableOfContentsRequest> | undefined): boolean {
    return proto3.util.equals(TableOfContentsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.TableOfContentsResponse
 */
export class TableOfContentsResponse extends Message<TableOfContentsResponse> {
  /**
   * @generated from field: repeated ablibrary.types.PageContentRef items = 1;
   */
  items: PageContentRef[] = [];

  constructor(data?: PartialMessage<TableOfContentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.TableOfContentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "items", kind: "message", T: PageContentRef, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TableOfContentsResponse {
    return new TableOfContentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TableOfContentsResponse {
    return new TableOfContentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TableOfContentsResponse {
    return new TableOfContentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: TableOfContentsResponse | PlainMessage<TableOfContentsResponse> | undefined, b: TableOfContentsResponse | PlainMessage<TableOfContentsResponse> | undefined): boolean {
    return proto3.util.equals(TableOfContentsResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.ContentsRequest
 */
export class ContentsRequest extends Message<ContentsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string book_id = 2;
   */
  bookId = "";

  /**
   * If page_numbers is not set, all pages are returned. If page_ids is set, this field will be ignored.
   *
   * @generated from field: repeated int32 page_numbers = 3;
   */
  pageNumbers: number[] = [];

  /**
   * @generated from field: repeated string page_ids = 4;
   */
  pageIds: string[] = [];

  constructor(data?: PartialMessage<ContentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.ContentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mask", kind: "message", T: FieldMask, opt: true },
    { no: 2, name: "book_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page_numbers", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 4, name: "page_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ContentsRequest {
    return new ContentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ContentsRequest {
    return new ContentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ContentsRequest {
    return new ContentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ContentsRequest | PlainMessage<ContentsRequest> | undefined, b: ContentsRequest | PlainMessage<ContentsRequest> | undefined): boolean {
    return proto3.util.equals(ContentsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.ContentsResponse
 */
export class ContentsResponse extends Message<ContentsResponse> {
  /**
   * @generated from field: repeated ablibrary.types.Page pages = 1;
   */
  pages: Page[] = [];

  constructor(data?: PartialMessage<ContentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.ContentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pages", kind: "message", T: Page, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ContentsResponse {
    return new ContentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ContentsResponse {
    return new ContentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ContentsResponse {
    return new ContentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ContentsResponse | PlainMessage<ContentsResponse> | undefined, b: ContentsResponse | PlainMessage<ContentsResponse> | undefined): boolean {
    return proto3.util.equals(ContentsResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.HTMLContentsRequest
 */
export class HTMLContentsRequest extends Message<HTMLContentsRequest> {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId = "";

  /**
   * If page_numbers is not set, all pages are returned. If page_ids is set, this field will be ignored.
   *
   * @generated from field: repeated int32 page_numbers = 2;
   */
  pageNumbers: number[] = [];

  /**
   * @generated from field: repeated string page_ids = 3;
   */
  pageIds: string[] = [];

  /**
   * @generated from field: repeated ablibrary.services.book_service.HTMLContentOption options = 4;
   */
  options: HTMLContentOption[] = [];

  constructor(data?: PartialMessage<HTMLContentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.HTMLContentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "book_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page_numbers", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 3, name: "page_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "options", kind: "enum", T: proto3.getEnumType(HTMLContentOption), repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HTMLContentsRequest {
    return new HTMLContentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HTMLContentsRequest {
    return new HTMLContentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HTMLContentsRequest {
    return new HTMLContentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: HTMLContentsRequest | PlainMessage<HTMLContentsRequest> | undefined, b: HTMLContentsRequest | PlainMessage<HTMLContentsRequest> | undefined): boolean {
    return proto3.util.equals(HTMLContentsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.HTMLContentsResponse
 */
export class HTMLContentsResponse extends Message<HTMLContentsResponse> {
  /**
   * @generated from field: string data = 1;
   */
  data = "";

  constructor(data?: PartialMessage<HTMLContentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.HTMLContentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HTMLContentsResponse {
    return new HTMLContentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HTMLContentsResponse {
    return new HTMLContentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HTMLContentsResponse {
    return new HTMLContentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: HTMLContentsResponse | PlainMessage<HTMLContentsResponse> | undefined, b: HTMLContentsResponse | PlainMessage<HTMLContentsResponse> | undefined): boolean {
    return proto3.util.equals(HTMLContentsResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.PDFContentsRequest
 */
export class PDFContentsRequest extends Message<PDFContentsRequest> {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId = "";

  /**
   * If page_numbers is not set, all pages are returned. If page_ids is set, this field will be ignored.
   *
   * @generated from field: repeated int32 page_numbers = 2;
   */
  pageNumbers: number[] = [];

  /**
   * @generated from field: repeated string page_ids = 3;
   */
  pageIds: string[] = [];

  constructor(data?: PartialMessage<PDFContentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.PDFContentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "book_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page_numbers", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
    { no: 3, name: "page_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PDFContentsRequest {
    return new PDFContentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PDFContentsRequest {
    return new PDFContentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PDFContentsRequest {
    return new PDFContentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PDFContentsRequest | PlainMessage<PDFContentsRequest> | undefined, b: PDFContentsRequest | PlainMessage<PDFContentsRequest> | undefined): boolean {
    return proto3.util.equals(PDFContentsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.PDFContentsResponse
 */
export class PDFContentsResponse extends Message<PDFContentsResponse> {
  constructor(data?: PartialMessage<PDFContentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.PDFContentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PDFContentsResponse {
    return new PDFContentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PDFContentsResponse {
    return new PDFContentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PDFContentsResponse {
    return new PDFContentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PDFContentsResponse | PlainMessage<PDFContentsResponse> | undefined, b: PDFContentsResponse | PlainMessage<PDFContentsResponse> | undefined): boolean {
    return proto3.util.equals(PDFContentsResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.FindRequest
 */
export class FindRequest extends Message<FindRequest> {
  constructor(data?: PartialMessage<FindRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.FindRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FindRequest {
    return new FindRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FindRequest {
    return new FindRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FindRequest {
    return new FindRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FindRequest | PlainMessage<FindRequest> | undefined, b: FindRequest | PlainMessage<FindRequest> | undefined): boolean {
    return proto3.util.equals(FindRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.FindResponse
 */
export class FindResponse extends Message<FindResponse> {
  constructor(data?: PartialMessage<FindResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.FindResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FindResponse {
    return new FindResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FindResponse {
    return new FindResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FindResponse {
    return new FindResponse().fromJsonString(jsonString, options);
  }

  static equals(a: FindResponse | PlainMessage<FindResponse> | undefined, b: FindResponse | PlainMessage<FindResponse> | undefined): boolean {
    return proto3.util.equals(FindResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.CloseBookRequest
 */
export class CloseBookRequest extends Message<CloseBookRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: optional string page_id = 2;
   */
  pageId?: string;

  constructor(data?: PartialMessage<CloseBookRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.CloseBookRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CloseBookRequest {
    return new CloseBookRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CloseBookRequest {
    return new CloseBookRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CloseBookRequest {
    return new CloseBookRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CloseBookRequest | PlainMessage<CloseBookRequest> | undefined, b: CloseBookRequest | PlainMessage<CloseBookRequest> | undefined): boolean {
    return proto3.util.equals(CloseBookRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.CloseBookResponse
 */
export class CloseBookResponse extends Message<CloseBookResponse> {
  constructor(data?: PartialMessage<CloseBookResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.CloseBookResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CloseBookResponse {
    return new CloseBookResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CloseBookResponse {
    return new CloseBookResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CloseBookResponse {
    return new CloseBookResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CloseBookResponse | PlainMessage<CloseBookResponse> | undefined, b: CloseBookResponse | PlainMessage<CloseBookResponse> | undefined): boolean {
    return proto3.util.equals(CloseBookResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.GetSettingsRequest
 */
export class GetSettingsRequest extends Message<GetSettingsRequest> {
  constructor(data?: PartialMessage<GetSettingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.GetSettingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSettingsRequest {
    return new GetSettingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSettingsRequest {
    return new GetSettingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSettingsRequest {
    return new GetSettingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSettingsRequest | PlainMessage<GetSettingsRequest> | undefined, b: GetSettingsRequest | PlainMessage<GetSettingsRequest> | undefined): boolean {
    return proto3.util.equals(GetSettingsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.GetSettingsResponse
 */
export class GetSettingsResponse extends Message<GetSettingsResponse> {
  /**
   * @generated from field: ablibrary.services.book_service.Settings settings = 1;
   */
  settings?: Settings;

  constructor(data?: PartialMessage<GetSettingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.GetSettingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "settings", kind: "message", T: Settings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSettingsResponse {
    return new GetSettingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSettingsResponse {
    return new GetSettingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSettingsResponse {
    return new GetSettingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetSettingsResponse | PlainMessage<GetSettingsResponse> | undefined, b: GetSettingsResponse | PlainMessage<GetSettingsResponse> | undefined): boolean {
    return proto3.util.equals(GetSettingsResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.SetSettingsRequest
 */
export class SetSettingsRequest extends Message<SetSettingsRequest> {
  /**
   * @generated from field: ablibrary.services.book_service.Settings settings = 1;
   */
  settings?: Settings;

  constructor(data?: PartialMessage<SetSettingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.SetSettingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "settings", kind: "message", T: Settings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSettingsRequest {
    return new SetSettingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSettingsRequest {
    return new SetSettingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSettingsRequest {
    return new SetSettingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetSettingsRequest | PlainMessage<SetSettingsRequest> | undefined, b: SetSettingsRequest | PlainMessage<SetSettingsRequest> | undefined): boolean {
    return proto3.util.equals(SetSettingsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.SetSettingsResponse
 */
export class SetSettingsResponse extends Message<SetSettingsResponse> {
  constructor(data?: PartialMessage<SetSettingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.SetSettingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSettingsResponse {
    return new SetSettingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSettingsResponse {
    return new SetSettingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSettingsResponse {
    return new SetSettingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SetSettingsResponse | PlainMessage<SetSettingsResponse> | undefined, b: SetSettingsResponse | PlainMessage<SetSettingsResponse> | undefined): boolean {
    return proto3.util.equals(SetSettingsResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.book_service.Settings
 */
export class Settings extends Message<Settings> {
  /**
   * @generated from field: string reader_font_family = 1;
   */
  readerFontFamily = "";

  /**
   * @generated from field: string reader_font_size = 2;
   */
  readerFontSize = "";

  /**
   * @generated from field: string reader_background_color = 3;
   */
  readerBackgroundColor = "";

  /**
   * @generated from field: string reader_font_color = 4;
   */
  readerFontColor = "";

  constructor(data?: PartialMessage<Settings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.book_service.Settings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reader_font_family", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "reader_font_size", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "reader_background_color", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "reader_font_color", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Settings {
    return new Settings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Settings {
    return new Settings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Settings {
    return new Settings().fromJsonString(jsonString, options);
  }

  static equals(a: Settings | PlainMessage<Settings> | undefined, b: Settings | PlainMessage<Settings> | undefined): boolean {
    return proto3.util.equals(Settings, a, b);
  }
}

