// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/localization_service/localization_service.proto (package ablibrary.services.localization_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Struct } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { FieldMask } from "../../types/field_mask_pb";
import type { LocalizedString } from "../../types/localized_string_pb";
import type { DateTime } from "../../types/common_pb";

/**
 * @generated from message ablibrary.services.localization_service.ListRequest
 */
export declare class ListRequest extends Message<ListRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: repeated string ids = 2;
   */
  ids: string[];

  /**
   * @generated from field: repeated string tokens = 3;
   */
  tokens: string[];

  /**
   * @generated from field: repeated string categories = 4;
   */
  categories: string[];

  /**
   * @generated from field: repeated string languages = 5;
   */
  languages: string[];

  constructor(data?: PartialMessage<ListRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.localization_service.ListRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest;

  static equals(a: ListRequest | PlainMessage<ListRequest> | undefined, b: ListRequest | PlainMessage<ListRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.localization_service.ListResponse
 */
export declare class ListResponse extends Message<ListResponse> {
  /**
   * @generated from field: repeated ablibrary.types.LocalizedString strings = 1;
   */
  strings: LocalizedString[];

  constructor(data?: PartialMessage<ListResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.localization_service.ListResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponse;

  static equals(a: ListResponse | PlainMessage<ListResponse> | undefined, b: ListResponse | PlainMessage<ListResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.localization_service.DetailsRequest
 */
export declare class DetailsRequest extends Message<DetailsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * @generated from field: optional string category = 3;
   */
  category?: string;

  constructor(data?: PartialMessage<DetailsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.localization_service.DetailsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsRequest;

  static equals(a: DetailsRequest | PlainMessage<DetailsRequest> | undefined, b: DetailsRequest | PlainMessage<DetailsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.localization_service.DetailsResponse
 */
export declare class DetailsResponse extends Message<DetailsResponse> {
  /**
   * @generated from field: ablibrary.types.LocalizedString localized_string = 1;
   */
  localizedString?: LocalizedString;

  constructor(data?: PartialMessage<DetailsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.localization_service.DetailsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsResponse;

  static equals(a: DetailsResponse | PlainMessage<DetailsResponse> | undefined, b: DetailsResponse | PlainMessage<DetailsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.localization_service.TranslateRequest
 */
export declare class TranslateRequest extends Message<TranslateRequest> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId: string;

  /**
   * @generated from field: optional google.protobuf.Struct parameters = 3;
   */
  parameters?: Struct;

  constructor(data?: PartialMessage<TranslateRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.localization_service.TranslateRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TranslateRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TranslateRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TranslateRequest;

  static equals(a: TranslateRequest | PlainMessage<TranslateRequest> | undefined, b: TranslateRequest | PlainMessage<TranslateRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.localization_service.TranslateResponse
 */
export declare class TranslateResponse extends Message<TranslateResponse> {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId: string;

  /**
   * @generated from field: string translation = 3;
   */
  translation: string;

  constructor(data?: PartialMessage<TranslateResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.localization_service.TranslateResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TranslateResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TranslateResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TranslateResponse;

  static equals(a: TranslateResponse | PlainMessage<TranslateResponse> | undefined, b: TranslateResponse | PlainMessage<TranslateResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.localization_service.LastUpdatedRequest
 */
export declare class LastUpdatedRequest extends Message<LastUpdatedRequest> {
  constructor(data?: PartialMessage<LastUpdatedRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.localization_service.LastUpdatedRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LastUpdatedRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LastUpdatedRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LastUpdatedRequest;

  static equals(a: LastUpdatedRequest | PlainMessage<LastUpdatedRequest> | undefined, b: LastUpdatedRequest | PlainMessage<LastUpdatedRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.localization_service.LastUpdatedResponse
 */
export declare class LastUpdatedResponse extends Message<LastUpdatedResponse> {
  /**
   * @generated from field: ablibrary.types.DateTime last_updated = 1;
   */
  lastUpdated?: DateTime;

  constructor(data?: PartialMessage<LastUpdatedResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.localization_service.LastUpdatedResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LastUpdatedResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LastUpdatedResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LastUpdatedResponse;

  static equals(a: LastUpdatedResponse | PlainMessage<LastUpdatedResponse> | undefined, b: LastUpdatedResponse | PlainMessage<LastUpdatedResponse> | undefined): boolean;
}

