// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/collection_service/collection_service.proto (package ablibrary.services.collection_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { FieldMask } from "../../types/field_mask_pb";
import type { Bookmark, Collection } from "../../types/bookmark_pb";
import type { Pagination } from "../../types/pagination_pb";

/**
 * @generated from message ablibrary.services.collection_service.ListRequest
 */
export declare class ListRequest extends Message<ListRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  constructor(data?: PartialMessage<ListRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.ListRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest;

  static equals(a: ListRequest | PlainMessage<ListRequest> | undefined, b: ListRequest | PlainMessage<ListRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.ListResponse
 */
export declare class ListResponse extends Message<ListResponse> {
  /**
   * @generated from field: repeated ablibrary.types.Collection collections = 1;
   */
  collections: Collection[];

  /**
   * @generated from field: ablibrary.types.Pagination pagination = 2;
   */
  pagination?: Pagination;

  constructor(data?: PartialMessage<ListResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.ListResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponse;

  static equals(a: ListResponse | PlainMessage<ListResponse> | undefined, b: ListResponse | PlainMessage<ListResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.DetailsRequest
 */
export declare class DetailsRequest extends Message<DetailsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  constructor(data?: PartialMessage<DetailsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.DetailsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsRequest;

  static equals(a: DetailsRequest | PlainMessage<DetailsRequest> | undefined, b: DetailsRequest | PlainMessage<DetailsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.DetailsResponse
 */
export declare class DetailsResponse extends Message<DetailsResponse> {
  /**
   * @generated from field: ablibrary.types.Collection collection = 1;
   */
  collection?: Collection;

  constructor(data?: PartialMessage<DetailsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.DetailsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsResponse;

  static equals(a: DetailsResponse | PlainMessage<DetailsResponse> | undefined, b: DetailsResponse | PlainMessage<DetailsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.UpsertRequest
 */
export declare class UpsertRequest extends Message<UpsertRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: ablibrary.types.Collection collection = 2;
   */
  collection?: Collection;

  constructor(data?: PartialMessage<UpsertRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.UpsertRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpsertRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpsertRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpsertRequest;

  static equals(a: UpsertRequest | PlainMessage<UpsertRequest> | undefined, b: UpsertRequest | PlainMessage<UpsertRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.UpsertResponse
 */
export declare class UpsertResponse extends Message<UpsertResponse> {
  /**
   * @generated from field: ablibrary.types.Collection collection = 1;
   */
  collection?: Collection;

  constructor(data?: PartialMessage<UpsertResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.UpsertResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpsertResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpsertResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpsertResponse;

  static equals(a: UpsertResponse | PlainMessage<UpsertResponse> | undefined, b: UpsertResponse | PlainMessage<UpsertResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.DeleteRequest
 */
export declare class DeleteRequest extends Message<DeleteRequest> {
  /**
   * @generated from field: repeated string collection_ids = 1;
   */
  collectionIds: string[];

  constructor(data?: PartialMessage<DeleteRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.DeleteRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteRequest;

  static equals(a: DeleteRequest | PlainMessage<DeleteRequest> | undefined, b: DeleteRequest | PlainMessage<DeleteRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.DeleteResponse
 */
export declare class DeleteResponse extends Message<DeleteResponse> {
  constructor(data?: PartialMessage<DeleteResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.DeleteResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteResponse;

  static equals(a: DeleteResponse | PlainMessage<DeleteResponse> | undefined, b: DeleteResponse | PlainMessage<DeleteResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.UpsertBookmarkRequest
 */
export declare class UpsertBookmarkRequest extends Message<UpsertBookmarkRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: ablibrary.types.Bookmark bookmark = 2;
   */
  bookmark?: Bookmark;

  constructor(data?: PartialMessage<UpsertBookmarkRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.UpsertBookmarkRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpsertBookmarkRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpsertBookmarkRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpsertBookmarkRequest;

  static equals(a: UpsertBookmarkRequest | PlainMessage<UpsertBookmarkRequest> | undefined, b: UpsertBookmarkRequest | PlainMessage<UpsertBookmarkRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.UpsertBookmarkResponse
 */
export declare class UpsertBookmarkResponse extends Message<UpsertBookmarkResponse> {
  /**
   * @generated from field: ablibrary.types.Bookmark bookmark = 1;
   */
  bookmark?: Bookmark;

  constructor(data?: PartialMessage<UpsertBookmarkResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.UpsertBookmarkResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpsertBookmarkResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpsertBookmarkResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpsertBookmarkResponse;

  static equals(a: UpsertBookmarkResponse | PlainMessage<UpsertBookmarkResponse> | undefined, b: UpsertBookmarkResponse | PlainMessage<UpsertBookmarkResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.DeleteBookmarkRequest
 */
export declare class DeleteBookmarkRequest extends Message<DeleteBookmarkRequest> {
  /**
   * @generated from field: repeated string bookmark_ids = 1;
   */
  bookmarkIds: string[];

  constructor(data?: PartialMessage<DeleteBookmarkRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.DeleteBookmarkRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteBookmarkRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteBookmarkRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteBookmarkRequest;

  static equals(a: DeleteBookmarkRequest | PlainMessage<DeleteBookmarkRequest> | undefined, b: DeleteBookmarkRequest | PlainMessage<DeleteBookmarkRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.collection_service.DeleteBookmarkResponse
 */
export declare class DeleteBookmarkResponse extends Message<DeleteBookmarkResponse> {
  constructor(data?: PartialMessage<DeleteBookmarkResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.collection_service.DeleteBookmarkResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteBookmarkResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteBookmarkResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteBookmarkResponse;

  static equals(a: DeleteBookmarkResponse | PlainMessage<DeleteBookmarkResponse> | undefined, b: DeleteBookmarkResponse | PlainMessage<DeleteBookmarkResponse> | undefined): boolean;
}

