// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/collection_service/collection_service.proto (package ablibrary.services.collection_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddBookToCollectionRequest, AddBookToCollectionResponse, DeleteBookmarkRequest, DeleteBookmarkResponse, DeleteRequest, DeleteResponse, DetailsRequest, DetailsResponse, ListBookmarksRequest, ListBookmarksResponse, ListRequest, ListResponse, RemoveBookFromCollectionRequest, RemoveBookFromCollectionResponse, UpsertBookmarkRequest, UpsertBookmarkResponse, UpsertRequest, UpsertResponse } from "./collection_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.collection_service.CollectionService
 */
export declare const CollectionService: {
  readonly typeName: "ablibrary.services.collection_service.CollectionService",
  readonly methods: {
    /**
     * @generated from rpc ablibrary.services.collection_service.CollectionService.List
     */
    readonly list: {
      readonly name: "List",
      readonly I: typeof ListRequest,
      readonly O: typeof ListResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.collection_service.CollectionService.Details
     */
    readonly details: {
      readonly name: "Details",
      readonly I: typeof DetailsRequest,
      readonly O: typeof DetailsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.collection_service.CollectionService.Upsert
     */
    readonly upsert: {
      readonly name: "Upsert",
      readonly I: typeof UpsertRequest,
      readonly O: typeof UpsertResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.collection_service.CollectionService.Delete
     */
    readonly delete: {
      readonly name: "Delete",
      readonly I: typeof DeleteRequest,
      readonly O: typeof DeleteResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.collection_service.CollectionService.AddBookToCollection
     */
    readonly addBookToCollection: {
      readonly name: "AddBookToCollection",
      readonly I: typeof AddBookToCollectionRequest,
      readonly O: typeof AddBookToCollectionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.collection_service.CollectionService.RemoveBookFromCollection
     */
    readonly removeBookFromCollection: {
      readonly name: "RemoveBookFromCollection",
      readonly I: typeof RemoveBookFromCollectionRequest,
      readonly O: typeof RemoveBookFromCollectionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.collection_service.CollectionService.UpsertBookmark
     */
    readonly upsertBookmark: {
      readonly name: "UpsertBookmark",
      readonly I: typeof UpsertBookmarkRequest,
      readonly O: typeof UpsertBookmarkResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.collection_service.CollectionService.DeleteBookmark
     */
    readonly deleteBookmark: {
      readonly name: "DeleteBookmark",
      readonly I: typeof DeleteBookmarkRequest,
      readonly O: typeof DeleteBookmarkResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.collection_service.CollectionService.ListBookmarks
     */
    readonly listBookmarks: {
      readonly name: "ListBookmarks",
      readonly I: typeof ListBookmarksRequest,
      readonly O: typeof ListBookmarksResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

