// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/country_service/country_service.proto (package ablibrary.services.country_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { FieldMask } from "../../types/field_mask_pb";
import { Country } from "../../types/country_pb";

/**
 * @generated from message ablibrary.services.country_service.ListRequest
 */
export class ListRequest extends Message<ListRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  constructor(data?: PartialMessage<ListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.country_service.ListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mask", kind: "message", T: FieldMask, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest {
    return new ListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest {
    return new ListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest {
    return new ListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest | PlainMessage<ListRequest> | undefined, b: ListRequest | PlainMessage<ListRequest> | undefined): boolean {
    return proto3.util.equals(ListRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.country_service.ListResponse
 */
export class ListResponse extends Message<ListResponse> {
  /**
   * @generated from field: repeated ablibrary.types.Country countries = 1;
   */
  countries: Country[] = [];

  constructor(data?: PartialMessage<ListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.country_service.ListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "countries", kind: "message", T: Country, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponse {
    return new ListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponse {
    return new ListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponse {
    return new ListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListResponse | PlainMessage<ListResponse> | undefined, b: ListResponse | PlainMessage<ListResponse> | undefined): boolean {
    return proto3.util.equals(ListResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.country_service.DetailsRequest
 */
export class DetailsRequest extends Message<DetailsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string id = 2;
   */
  id = "";

  constructor(data?: PartialMessage<DetailsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.country_service.DetailsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mask", kind: "message", T: FieldMask, opt: true },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsRequest {
    return new DetailsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsRequest {
    return new DetailsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsRequest {
    return new DetailsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DetailsRequest | PlainMessage<DetailsRequest> | undefined, b: DetailsRequest | PlainMessage<DetailsRequest> | undefined): boolean {
    return proto3.util.equals(DetailsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.country_service.DetailsResponse
 */
export class DetailsResponse extends Message<DetailsResponse> {
  /**
   * @generated from field: ablibrary.types.Country country = 1;
   */
  country?: Country;

  constructor(data?: PartialMessage<DetailsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.country_service.DetailsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "country", kind: "message", T: Country },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsResponse {
    return new DetailsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsResponse {
    return new DetailsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsResponse {
    return new DetailsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DetailsResponse | PlainMessage<DetailsResponse> | undefined, b: DetailsResponse | PlainMessage<DetailsResponse> | undefined): boolean {
    return proto3.util.equals(DetailsResponse, a, b);
  }
}

