// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/user_service/user_service.proto (package ablibrary.services.user_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChangeLanguageRequest, ChangeLanguageResponse, ChangePasswordRequest, ChangePasswordResponse, ForgotPasswordRequest, ForgotPasswordResponse, LoginRequest, LoginResponse, LogoutRequest, LogoutResponse, ProfileRequest, ProfileResponse, RegisterRequest, RegisterResponse, ResetPasswordRequest, ResetPasswordResponse, UpdateAvatarRequest, UpdateAvatarResponse, UpdateProfileRequest, UpdateProfileResponse, VerifyEmailRequest, VerifyEmailResponse } from "./user_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.user_service.UserService
 */
export declare const UserService: {
  readonly typeName: "ablibrary.services.user_service.UserService",
  readonly methods: {
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.Login
     */
    readonly login: {
      readonly name: "Login",
      readonly I: typeof LoginRequest,
      readonly O: typeof LoginResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.Register
     */
    readonly register: {
      readonly name: "Register",
      readonly I: typeof RegisterRequest,
      readonly O: typeof RegisterResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.VerifyEmail
     */
    readonly verifyEmail: {
      readonly name: "VerifyEmail",
      readonly I: typeof VerifyEmailRequest,
      readonly O: typeof VerifyEmailResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.ForgotPassword
     */
    readonly forgotPassword: {
      readonly name: "ForgotPassword",
      readonly I: typeof ForgotPasswordRequest,
      readonly O: typeof ForgotPasswordResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.ResetPassword
     */
    readonly resetPassword: {
      readonly name: "ResetPassword",
      readonly I: typeof ResetPasswordRequest,
      readonly O: typeof ResetPasswordResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.Logout
     */
    readonly logout: {
      readonly name: "Logout",
      readonly I: typeof LogoutRequest,
      readonly O: typeof LogoutResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.Profile
     */
    readonly profile: {
      readonly name: "Profile",
      readonly I: typeof ProfileRequest,
      readonly O: typeof ProfileResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.UpdateProfile
     */
    readonly updateProfile: {
      readonly name: "UpdateProfile",
      readonly I: typeof UpdateProfileRequest,
      readonly O: typeof UpdateProfileResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.UpdateAvatar
     */
    readonly updateAvatar: {
      readonly name: "UpdateAvatar",
      readonly I: typeof UpdateAvatarRequest,
      readonly O: typeof UpdateAvatarResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.ChangePassword
     */
    readonly changePassword: {
      readonly name: "ChangePassword",
      readonly I: typeof ChangePasswordRequest,
      readonly O: typeof ChangePasswordResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.user_service.UserService.ChangeLanguage
     */
    readonly changeLanguage: {
      readonly name: "ChangeLanguage",
      readonly I: typeof ChangeLanguageRequest,
      readonly O: typeof ChangeLanguageResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

