// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/search_service/search_service.proto (package ablibrary.services.search_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ClearHistoryRequest, ClearHistoryResponse, DeleteHistoryRequest, DeleteHistoryResponse, GetSettingsRequest, GetSettingsResponse, HistoryRequest, HistoryResponse, SearchInBookRequest, SearchInBookResponse, SearchRequest, SearchResponse, SetSettingsRequest, SetSettingsResponse, SuggestRequest, SuggestResponse } from "./search_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.search_service.SearchService
 */
export declare const SearchService: {
  readonly typeName: "ablibrary.services.search_service.SearchService",
  readonly methods: {
    /**
     * @generated from rpc ablibrary.services.search_service.SearchService.Search
     */
    readonly search: {
      readonly name: "Search",
      readonly I: typeof SearchRequest,
      readonly O: typeof SearchResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.search_service.SearchService.SearchInBook
     */
    readonly searchInBook: {
      readonly name: "SearchInBook",
      readonly I: typeof SearchInBookRequest,
      readonly O: typeof SearchInBookResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.search_service.SearchService.Suggest
     */
    readonly suggest: {
      readonly name: "Suggest",
      readonly I: typeof SuggestRequest,
      readonly O: typeof SuggestResponse,
      readonly kind: MethodKind.BiDiStreaming,
    },
    /**
     * @generated from rpc ablibrary.services.search_service.SearchService.History
     */
    readonly history: {
      readonly name: "History",
      readonly I: typeof HistoryRequest,
      readonly O: typeof HistoryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.search_service.SearchService.DeleteHistory
     */
    readonly deleteHistory: {
      readonly name: "DeleteHistory",
      readonly I: typeof DeleteHistoryRequest,
      readonly O: typeof DeleteHistoryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.search_service.SearchService.ClearHistory
     */
    readonly clearHistory: {
      readonly name: "ClearHistory",
      readonly I: typeof ClearHistoryRequest,
      readonly O: typeof ClearHistoryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.search_service.SearchService.GetSettings
     */
    readonly getSettings: {
      readonly name: "GetSettings",
      readonly I: typeof GetSettingsRequest,
      readonly O: typeof GetSettingsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.search_service.SearchService.SetSettings
     */
    readonly setSettings: {
      readonly name: "SetSettings",
      readonly I: typeof SetSettingsRequest,
      readonly O: typeof SetSettingsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

