// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/language_service/language_service.proto (package ablibrary.services.language_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DetailsRequest, DetailsResponse, ListRequest, ListResponse, SetPreferredRequest, SetPreferredResponse } from "./language_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.language_service.LanguageService
 */
export declare const LanguageService: {
  readonly typeName: "ablibrary.services.language_service.LanguageService",
  readonly methods: {
    /**
     * @generated from rpc ablibrary.services.language_service.LanguageService.List
     */
    readonly list: {
      readonly name: "List",
      readonly I: typeof ListRequest,
      readonly O: typeof ListResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.language_service.LanguageService.Details
     */
    readonly details: {
      readonly name: "Details",
      readonly I: typeof DetailsRequest,
      readonly O: typeof DetailsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.language_service.LanguageService.SetPreferred
     */
    readonly setPreferred: {
      readonly name: "SetPreferred",
      readonly I: typeof SetPreferredRequest,
      readonly O: typeof SetPreferredResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

