// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/language_service/language_service.proto (package ablibrary.services.language_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DetailsRequest, DetailsResponse, ListRequest, ListResponse, SetPreferredRequest, SetPreferredResponse } from "./language_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.language_service.LanguageService
 */
export const LanguageService = {
  typeName: "ablibrary.services.language_service.LanguageService",
  methods: {
    /**
     * @generated from rpc ablibrary.services.language_service.LanguageService.List
     */
    list: {
      name: "List",
      I: ListRequest,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.language_service.LanguageService.Details
     */
    details: {
      name: "Details",
      I: DetailsRequest,
      O: DetailsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.language_service.LanguageService.SetPreferred
     */
    setPreferred: {
      name: "SetPreferred",
      I: SetPreferredRequest,
      O: SetPreferredResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

