// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/contributor_service/contributor_service.proto (package ablibrary.services.contributor_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DetailsRequest, DetailsResponse, ListRequest, ListResponse } from "./contributor_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.contributor_service.ContributorService
 */
export declare const ContributorService: {
  readonly typeName: "ablibrary.services.contributor_service.ContributorService",
  readonly methods: {
    /**
     * @generated from rpc ablibrary.services.contributor_service.ContributorService.List
     */
    readonly list: {
      readonly name: "List",
      readonly I: typeof ListRequest,
      readonly O: typeof ListResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.contributor_service.ContributorService.Details
     */
    readonly details: {
      readonly name: "Details",
      readonly I: typeof DetailsRequest,
      readonly O: typeof DetailsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

