// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/schema/book_tag_schema.proto (package ablibrary.schema, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_ablibrary_types_common } from "../types/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/schema/book_tag_schema.proto.
 */
export const file_ablibrary_schema_book_tag_schema: GenFile = /*@__PURE__*/
  fileDesc("CiZhYmxpYnJhcnkvc2NoZW1hL2Jvb2tfdGFnX3NjaGVtYS5wcm90bxIQYWJsaWJyYXJ5LnNjaGVtYSJACg1Cb29rVGFnU2NoZW1hEg8KB2Jvb2tfaWQYASABKAkSDgoGdGFnX2lkGAIgASgJEg4KBndlaWdodBgDIAEoBSLeAgoUQm9va1RhZ1NjaGVtYUZpbHRlcnMSPgoHYm9va19pZBgBIAMoCzItLmFibGlicmFyeS5zY2hlbWEuQm9va1RhZ1NjaGVtYUZpbHRlcnMuQm9va0lkEjwKBnRhZ19pZBgCIAMoCzIsLmFibGlicmFyeS5zY2hlbWEuQm9va1RhZ1NjaGVtYUZpbHRlcnMuVGFnSWQSPQoGd2VpZ2h0GAMgAygLMi0uYWJsaWJyYXJ5LnNjaGVtYS5Cb29rVGFnU2NoZW1hRmlsdGVycy5XZWlnaHQaJAoGQm9va0lkEgoKAmVxGAEgAygJEg4KBm5vdF9lcRgCIAMoCRojCgVUYWdJZBIKCgJlcRgBIAMoCRIOCgZub3RfZXEYAiADKAkaPgoGV2VpZ2h0EgoKAmVxGAEgAygFEg4KBm5vdF9lcRgCIAMoBRILCgNndGUYAyABKAUSCwoDbHRlGAQgASgFIjIKD0Jvb2tUYWdTY2hlbWFJRBIPCgdib29rX2lkGAEgASgJEg4KBnRhZ19pZBgCIAEoCSp7ChJCb29rVGFnU2NoZW1hRmllbGQSIQodQk9PS19UQUdfU0NIRU1BX0ZJRUxEX0JPT0tfSUQQABIgChxCT09LX1RBR19TQ0hFTUFfRklFTERfVEFHX0lEEAESIAocQk9PS19UQUdfU0NIRU1BX0ZJRUxEX1dFSUdIVBACQjNaHmFibGlicmFyeS5uZXQvYXBpL3Byb3RvL3NjaGVtYaoCEEFCTGlicmFyeS5TY2hlbWFiCGVkaXRpb25zcOgH", [file_ablibrary_types_common]);

/**
 * @generated from message ablibrary.schema.BookTagSchema
 */
export type BookTagSchema = Message<"ablibrary.schema.BookTagSchema"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * @generated from field: string tag_id = 2;
   */
  tagId: string;

  /**
   * @generated from field: int32 weight = 3;
   */
  weight: number;
};

/**
 * @generated from message ablibrary.schema.BookTagSchema
 */
export type BookTagSchemaJson = {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId?: string;

  /**
   * @generated from field: string tag_id = 2;
   */
  tagId?: string;

  /**
   * @generated from field: int32 weight = 3;
   */
  weight?: number;
};

/**
 * Describes the message ablibrary.schema.BookTagSchema.
 * Use `create(BookTagSchemaSchema)` to create a new message.
 */
export const BookTagSchemaSchema: GenMessage<BookTagSchema, {jsonType: BookTagSchemaJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_book_tag_schema, 0);

/**
 * @generated from message ablibrary.schema.BookTagSchemaFilters
 */
export type BookTagSchemaFilters = Message<"ablibrary.schema.BookTagSchemaFilters"> & {
  /**
   * @generated from field: repeated ablibrary.schema.BookTagSchemaFilters.BookId book_id = 1;
   */
  bookId: BookTagSchemaFilters_BookId[];

  /**
   * @generated from field: repeated ablibrary.schema.BookTagSchemaFilters.TagId tag_id = 2;
   */
  tagId: BookTagSchemaFilters_TagId[];

  /**
   * @generated from field: repeated ablibrary.schema.BookTagSchemaFilters.Weight weight = 3;
   */
  weight: BookTagSchemaFilters_Weight[];
};

/**
 * @generated from message ablibrary.schema.BookTagSchemaFilters
 */
export type BookTagSchemaFiltersJson = {
  /**
   * @generated from field: repeated ablibrary.schema.BookTagSchemaFilters.BookId book_id = 1;
   */
  bookId?: BookTagSchemaFilters_BookIdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.BookTagSchemaFilters.TagId tag_id = 2;
   */
  tagId?: BookTagSchemaFilters_TagIdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.BookTagSchemaFilters.Weight weight = 3;
   */
  weight?: BookTagSchemaFilters_WeightJson[];
};

/**
 * Describes the message ablibrary.schema.BookTagSchemaFilters.
 * Use `create(BookTagSchemaFiltersSchema)` to create a new message.
 */
export const BookTagSchemaFiltersSchema: GenMessage<BookTagSchemaFilters, {jsonType: BookTagSchemaFiltersJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_book_tag_schema, 1);

/**
 * @generated from message ablibrary.schema.BookTagSchemaFilters.BookId
 */
export type BookTagSchemaFilters_BookId = Message<"ablibrary.schema.BookTagSchemaFilters.BookId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.BookTagSchemaFilters.BookId
 */
export type BookTagSchemaFilters_BookIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.BookTagSchemaFilters.BookId.
 * Use `create(BookTagSchemaFilters_BookIdSchema)` to create a new message.
 */
export const BookTagSchemaFilters_BookIdSchema: GenMessage<BookTagSchemaFilters_BookId, {jsonType: BookTagSchemaFilters_BookIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_book_tag_schema, 1, 0);

/**
 * @generated from message ablibrary.schema.BookTagSchemaFilters.TagId
 */
export type BookTagSchemaFilters_TagId = Message<"ablibrary.schema.BookTagSchemaFilters.TagId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.BookTagSchemaFilters.TagId
 */
export type BookTagSchemaFilters_TagIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.BookTagSchemaFilters.TagId.
 * Use `create(BookTagSchemaFilters_TagIdSchema)` to create a new message.
 */
export const BookTagSchemaFilters_TagIdSchema: GenMessage<BookTagSchemaFilters_TagId, {jsonType: BookTagSchemaFilters_TagIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_book_tag_schema, 1, 1);

/**
 * @generated from message ablibrary.schema.BookTagSchemaFilters.Weight
 */
export type BookTagSchemaFilters_Weight = Message<"ablibrary.schema.BookTagSchemaFilters.Weight"> & {
  /**
   * @generated from field: repeated int32 eq = 1;
   */
  eq: number[];

  /**
   * @generated from field: repeated int32 not_eq = 2;
   */
  notEq: number[];

  /**
   * @generated from field: int32 gte = 3;
   */
  gte: number;

  /**
   * @generated from field: int32 lte = 4;
   */
  lte: number;
};

/**
 * @generated from message ablibrary.schema.BookTagSchemaFilters.Weight
 */
export type BookTagSchemaFilters_WeightJson = {
  /**
   * @generated from field: repeated int32 eq = 1;
   */
  eq?: number[];

  /**
   * @generated from field: repeated int32 not_eq = 2;
   */
  notEq?: number[];

  /**
   * @generated from field: int32 gte = 3;
   */
  gte?: number;

  /**
   * @generated from field: int32 lte = 4;
   */
  lte?: number;
};

/**
 * Describes the message ablibrary.schema.BookTagSchemaFilters.Weight.
 * Use `create(BookTagSchemaFilters_WeightSchema)` to create a new message.
 */
export const BookTagSchemaFilters_WeightSchema: GenMessage<BookTagSchemaFilters_Weight, {jsonType: BookTagSchemaFilters_WeightJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_book_tag_schema, 1, 2);

/**
 * @generated from message ablibrary.schema.BookTagSchemaID
 */
export type BookTagSchemaID = Message<"ablibrary.schema.BookTagSchemaID"> & {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId: string;

  /**
   * @generated from field: string tag_id = 2;
   */
  tagId: string;
};

/**
 * @generated from message ablibrary.schema.BookTagSchemaID
 */
export type BookTagSchemaIDJson = {
  /**
   * @generated from field: string book_id = 1;
   */
  bookId?: string;

  /**
   * @generated from field: string tag_id = 2;
   */
  tagId?: string;
};

/**
 * Describes the message ablibrary.schema.BookTagSchemaID.
 * Use `create(BookTagSchemaIDSchema)` to create a new message.
 */
export const BookTagSchemaIDSchema: GenMessage<BookTagSchemaID, {jsonType: BookTagSchemaIDJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_book_tag_schema, 2);

/**
 * @generated from enum ablibrary.schema.BookTagSchemaField
 */
export enum BookTagSchemaField {
  /**
   * @generated from enum value: BOOK_TAG_SCHEMA_FIELD_BOOK_ID = 0;
   */
  BOOK_ID = 0,

  /**
   * @generated from enum value: BOOK_TAG_SCHEMA_FIELD_TAG_ID = 1;
   */
  TAG_ID = 1,

  /**
   * @generated from enum value: BOOK_TAG_SCHEMA_FIELD_WEIGHT = 2;
   */
  WEIGHT = 2,
}

/**
 * @generated from enum ablibrary.schema.BookTagSchemaField
 */
export type BookTagSchemaFieldJson = "BOOK_TAG_SCHEMA_FIELD_BOOK_ID" | "BOOK_TAG_SCHEMA_FIELD_TAG_ID" | "BOOK_TAG_SCHEMA_FIELD_WEIGHT";

/**
 * Describes the enum ablibrary.schema.BookTagSchemaField.
 */
export const BookTagSchemaFieldSchema: GenEnum<BookTagSchemaField, BookTagSchemaFieldJson> = /*@__PURE__*/
  enumDesc(file_ablibrary_schema_book_tag_schema, 0);

