// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/schema/contribution_translation_schema.proto (package ablibrary.schema, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_ablibrary_types_common } from "../types/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/schema/contribution_translation_schema.proto.
 */
export const file_ablibrary_schema_contribution_translation_schema: GenFile = /*@__PURE__*/
  fileDesc("CjZhYmxpYnJhcnkvc2NoZW1hL2NvbnRyaWJ1dGlvbl90cmFuc2xhdGlvbl9zY2hlbWEucHJvdG8SEGFibGlicmFyeS5zY2hlbWEicAodQ29udHJpYnV0aW9uVHJhbnNsYXRpb25TY2hlbWESFwoPY29udHJpYnV0aW9uX2lkGAEgASgJEhMKC2xhbmd1YWdlX2lkGAIgASgJEgwKBG5hbWUYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkijAUKJENvbnRyaWJ1dGlvblRyYW5zbGF0aW9uU2NoZW1hRmlsdGVycxJeCg9jb250cmlidXRpb25faWQYASADKAsyRS5hYmxpYnJhcnkuc2NoZW1hLkNvbnRyaWJ1dGlvblRyYW5zbGF0aW9uU2NoZW1hRmlsdGVycy5Db250cmlidXRpb25JZBJWCgtsYW5ndWFnZV9pZBgCIAMoCzJBLmFibGlicmFyeS5zY2hlbWEuQ29udHJpYnV0aW9uVHJhbnNsYXRpb25TY2hlbWFGaWx0ZXJzLkxhbmd1YWdlSWQSSQoEbmFtZRgDIAMoCzI7LmFibGlicmFyeS5zY2hlbWEuQ29udHJpYnV0aW9uVHJhbnNsYXRpb25TY2hlbWFGaWx0ZXJzLk5hbWUSVwoLZGVzY3JpcHRpb24YBCADKAsyQi5hYmxpYnJhcnkuc2NoZW1hLkNvbnRyaWJ1dGlvblRyYW5zbGF0aW9uU2NoZW1hRmlsdGVycy5EZXNjcmlwdGlvbhosCg5Db250cmlidXRpb25JZBIKCgJlcRgBIAMoCRIOCgZub3RfZXEYAiADKAkaKAoKTGFuZ3VhZ2VJZBIKCgJlcRgBIAMoCRIOCgZub3RfZXEYAiADKAkaQgoETmFtZRIKCgJlcRgBIAMoCRIOCgZub3RfZXEYAiADKAkSDAoEbGlrZRgDIAMoCRIQCghub3RfbGlrZRgEIAMoCRpsCgtEZXNjcmlwdGlvbhIPCgdpc19udWxsGAEgASgIEhAKCG5vdF9udWxsGAIgASgIEgoKAmVxGAMgAygJEg4KBm5vdF9lcRgEIAMoCRIMCgRsaWtlGAUgAygJEhAKCG5vdF9saWtlGAYgAygJIk8KH0NvbnRyaWJ1dGlvblRyYW5zbGF0aW9uU2NoZW1hSUQSFwoPY29udHJpYnV0aW9uX2lkGAEgASgJEhMKC2xhbmd1YWdlX2lkGAIgASgJKv0BCiJDb250cmlidXRpb25UcmFuc2xhdGlvblNjaGVtYUZpZWxkEjkKNUNPTlRSSUJVVElPTl9UUkFOU0xBVElPTl9TQ0hFTUFfRklFTERfQ09OVFJJQlVUSU9OX0lEEAASNQoxQ09OVFJJQlVUSU9OX1RSQU5TTEFUSU9OX1NDSEVNQV9GSUVMRF9MQU5HVUFHRV9JRBABEi4KKkNPTlRSSUJVVElPTl9UUkFOU0xBVElPTl9TQ0hFTUFfRklFTERfTkFNRRACEjUKMUNPTlRSSUJVVElPTl9UUkFOU0xBVElPTl9TQ0hFTUFfRklFTERfREVTQ1JJUFRJT04QA0IzWh5hYmxpYnJhcnkubmV0L2FwaS9wcm90by9zY2hlbWGqAhBBQkxpYnJhcnkuU2NoZW1hYghlZGl0aW9uc3DoBw", [file_ablibrary_types_common]);

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchema
 */
export type ContributionTranslationSchema = Message<"ablibrary.schema.ContributionTranslationSchema"> & {
  /**
   * @generated from field: string contribution_id = 1;
   */
  contributionId: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;
};

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchema
 */
export type ContributionTranslationSchemaJson = {
  /**
   * @generated from field: string contribution_id = 1;
   */
  contributionId?: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId?: string;

  /**
   * @generated from field: string name = 3;
   */
  name?: string;

  /**
   * @generated from field: string description = 4;
   */
  description?: string;
};

/**
 * Describes the message ablibrary.schema.ContributionTranslationSchema.
 * Use `create(ContributionTranslationSchemaSchema)` to create a new message.
 */
export const ContributionTranslationSchemaSchema: GenMessage<ContributionTranslationSchema, {jsonType: ContributionTranslationSchemaJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_contribution_translation_schema, 0);

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters
 */
export type ContributionTranslationSchemaFilters = Message<"ablibrary.schema.ContributionTranslationSchemaFilters"> & {
  /**
   * @generated from field: repeated ablibrary.schema.ContributionTranslationSchemaFilters.ContributionId contribution_id = 1;
   */
  contributionId: ContributionTranslationSchemaFilters_ContributionId[];

  /**
   * @generated from field: repeated ablibrary.schema.ContributionTranslationSchemaFilters.LanguageId language_id = 2;
   */
  languageId: ContributionTranslationSchemaFilters_LanguageId[];

  /**
   * @generated from field: repeated ablibrary.schema.ContributionTranslationSchemaFilters.Name name = 3;
   */
  name: ContributionTranslationSchemaFilters_Name[];

  /**
   * @generated from field: repeated ablibrary.schema.ContributionTranslationSchemaFilters.Description description = 4;
   */
  description: ContributionTranslationSchemaFilters_Description[];
};

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters
 */
export type ContributionTranslationSchemaFiltersJson = {
  /**
   * @generated from field: repeated ablibrary.schema.ContributionTranslationSchemaFilters.ContributionId contribution_id = 1;
   */
  contributionId?: ContributionTranslationSchemaFilters_ContributionIdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.ContributionTranslationSchemaFilters.LanguageId language_id = 2;
   */
  languageId?: ContributionTranslationSchemaFilters_LanguageIdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.ContributionTranslationSchemaFilters.Name name = 3;
   */
  name?: ContributionTranslationSchemaFilters_NameJson[];

  /**
   * @generated from field: repeated ablibrary.schema.ContributionTranslationSchemaFilters.Description description = 4;
   */
  description?: ContributionTranslationSchemaFilters_DescriptionJson[];
};

/**
 * Describes the message ablibrary.schema.ContributionTranslationSchemaFilters.
 * Use `create(ContributionTranslationSchemaFiltersSchema)` to create a new message.
 */
export const ContributionTranslationSchemaFiltersSchema: GenMessage<ContributionTranslationSchemaFilters, {jsonType: ContributionTranslationSchemaFiltersJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_contribution_translation_schema, 1);

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters.ContributionId
 */
export type ContributionTranslationSchemaFilters_ContributionId = Message<"ablibrary.schema.ContributionTranslationSchemaFilters.ContributionId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters.ContributionId
 */
export type ContributionTranslationSchemaFilters_ContributionIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.ContributionTranslationSchemaFilters.ContributionId.
 * Use `create(ContributionTranslationSchemaFilters_ContributionIdSchema)` to create a new message.
 */
export const ContributionTranslationSchemaFilters_ContributionIdSchema: GenMessage<ContributionTranslationSchemaFilters_ContributionId, {jsonType: ContributionTranslationSchemaFilters_ContributionIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_contribution_translation_schema, 1, 0);

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters.LanguageId
 */
export type ContributionTranslationSchemaFilters_LanguageId = Message<"ablibrary.schema.ContributionTranslationSchemaFilters.LanguageId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters.LanguageId
 */
export type ContributionTranslationSchemaFilters_LanguageIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.ContributionTranslationSchemaFilters.LanguageId.
 * Use `create(ContributionTranslationSchemaFilters_LanguageIdSchema)` to create a new message.
 */
export const ContributionTranslationSchemaFilters_LanguageIdSchema: GenMessage<ContributionTranslationSchemaFilters_LanguageId, {jsonType: ContributionTranslationSchemaFilters_LanguageIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_contribution_translation_schema, 1, 1);

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters.Name
 */
export type ContributionTranslationSchemaFilters_Name = Message<"ablibrary.schema.ContributionTranslationSchemaFilters.Name"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];

  /**
   * @generated from field: repeated string like = 3;
   */
  like: string[];

  /**
   * @generated from field: repeated string not_like = 4;
   */
  notLike: string[];
};

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters.Name
 */
export type ContributionTranslationSchemaFilters_NameJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];

  /**
   * @generated from field: repeated string like = 3;
   */
  like?: string[];

  /**
   * @generated from field: repeated string not_like = 4;
   */
  notLike?: string[];
};

/**
 * Describes the message ablibrary.schema.ContributionTranslationSchemaFilters.Name.
 * Use `create(ContributionTranslationSchemaFilters_NameSchema)` to create a new message.
 */
export const ContributionTranslationSchemaFilters_NameSchema: GenMessage<ContributionTranslationSchemaFilters_Name, {jsonType: ContributionTranslationSchemaFilters_NameJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_contribution_translation_schema, 1, 2);

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters.Description
 */
export type ContributionTranslationSchemaFilters_Description = Message<"ablibrary.schema.ContributionTranslationSchemaFilters.Description"> & {
  /**
   * @generated from field: bool is_null = 1;
   */
  isNull: boolean;

  /**
   * @generated from field: bool not_null = 2;
   */
  notNull: boolean;

  /**
   * @generated from field: repeated string eq = 3;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 4;
   */
  notEq: string[];

  /**
   * @generated from field: repeated string like = 5;
   */
  like: string[];

  /**
   * @generated from field: repeated string not_like = 6;
   */
  notLike: string[];
};

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaFilters.Description
 */
export type ContributionTranslationSchemaFilters_DescriptionJson = {
  /**
   * @generated from field: bool is_null = 1;
   */
  isNull?: boolean;

  /**
   * @generated from field: bool not_null = 2;
   */
  notNull?: boolean;

  /**
   * @generated from field: repeated string eq = 3;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 4;
   */
  notEq?: string[];

  /**
   * @generated from field: repeated string like = 5;
   */
  like?: string[];

  /**
   * @generated from field: repeated string not_like = 6;
   */
  notLike?: string[];
};

/**
 * Describes the message ablibrary.schema.ContributionTranslationSchemaFilters.Description.
 * Use `create(ContributionTranslationSchemaFilters_DescriptionSchema)` to create a new message.
 */
export const ContributionTranslationSchemaFilters_DescriptionSchema: GenMessage<ContributionTranslationSchemaFilters_Description, {jsonType: ContributionTranslationSchemaFilters_DescriptionJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_contribution_translation_schema, 1, 3);

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaID
 */
export type ContributionTranslationSchemaID = Message<"ablibrary.schema.ContributionTranslationSchemaID"> & {
  /**
   * @generated from field: string contribution_id = 1;
   */
  contributionId: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId: string;
};

/**
 * @generated from message ablibrary.schema.ContributionTranslationSchemaID
 */
export type ContributionTranslationSchemaIDJson = {
  /**
   * @generated from field: string contribution_id = 1;
   */
  contributionId?: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId?: string;
};

/**
 * Describes the message ablibrary.schema.ContributionTranslationSchemaID.
 * Use `create(ContributionTranslationSchemaIDSchema)` to create a new message.
 */
export const ContributionTranslationSchemaIDSchema: GenMessage<ContributionTranslationSchemaID, {jsonType: ContributionTranslationSchemaIDJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_contribution_translation_schema, 2);

/**
 * @generated from enum ablibrary.schema.ContributionTranslationSchemaField
 */
export enum ContributionTranslationSchemaField {
  /**
   * @generated from enum value: CONTRIBUTION_TRANSLATION_SCHEMA_FIELD_CONTRIBUTION_ID = 0;
   */
  CONTRIBUTION_ID = 0,

  /**
   * @generated from enum value: CONTRIBUTION_TRANSLATION_SCHEMA_FIELD_LANGUAGE_ID = 1;
   */
  LANGUAGE_ID = 1,

  /**
   * @generated from enum value: CONTRIBUTION_TRANSLATION_SCHEMA_FIELD_NAME = 2;
   */
  NAME = 2,

  /**
   * @generated from enum value: CONTRIBUTION_TRANSLATION_SCHEMA_FIELD_DESCRIPTION = 3;
   */
  DESCRIPTION = 3,
}

/**
 * @generated from enum ablibrary.schema.ContributionTranslationSchemaField
 */
export type ContributionTranslationSchemaFieldJson = "CONTRIBUTION_TRANSLATION_SCHEMA_FIELD_CONTRIBUTION_ID" | "CONTRIBUTION_TRANSLATION_SCHEMA_FIELD_LANGUAGE_ID" | "CONTRIBUTION_TRANSLATION_SCHEMA_FIELD_NAME" | "CONTRIBUTION_TRANSLATION_SCHEMA_FIELD_DESCRIPTION";

/**
 * Describes the enum ablibrary.schema.ContributionTranslationSchemaField.
 */
export const ContributionTranslationSchemaFieldSchema: GenEnum<ContributionTranslationSchemaField, ContributionTranslationSchemaFieldJson> = /*@__PURE__*/
  enumDesc(file_ablibrary_schema_contribution_translation_schema, 0);

