// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/schema/tag_translation_schema.proto (package ablibrary.schema, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_ablibrary_types_common } from "../types/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/schema/tag_translation_schema.proto.
 */
export const file_ablibrary_schema_tag_translation_schema: GenFile = /*@__PURE__*/
  fileDesc("Ci1hYmxpYnJhcnkvc2NoZW1hL3RhZ190cmFuc2xhdGlvbl9zY2hlbWEucHJvdG8SEGFibGlicmFyeS5zY2hlbWEiXgoUVGFnVHJhbnNsYXRpb25TY2hlbWESDgoGdGFnX2lkGAEgASgJEhMKC2xhbmd1YWdlX2lkGAIgASgJEgwKBG5hbWUYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkixAQKG1RhZ1RyYW5zbGF0aW9uU2NoZW1hRmlsdGVycxJDCgZ0YWdfaWQYASADKAsyMy5hYmxpYnJhcnkuc2NoZW1hLlRhZ1RyYW5zbGF0aW9uU2NoZW1hRmlsdGVycy5UYWdJZBJNCgtsYW5ndWFnZV9pZBgCIAMoCzI4LmFibGlicmFyeS5zY2hlbWEuVGFnVHJhbnNsYXRpb25TY2hlbWFGaWx0ZXJzLkxhbmd1YWdlSWQSQAoEbmFtZRgDIAMoCzIyLmFibGlicmFyeS5zY2hlbWEuVGFnVHJhbnNsYXRpb25TY2hlbWFGaWx0ZXJzLk5hbWUSTgoLZGVzY3JpcHRpb24YBCADKAsyOS5hYmxpYnJhcnkuc2NoZW1hLlRhZ1RyYW5zbGF0aW9uU2NoZW1hRmlsdGVycy5EZXNjcmlwdGlvbhojCgVUYWdJZBIKCgJlcRgBIAMoCRIOCgZub3RfZXEYAiADKAkaKAoKTGFuZ3VhZ2VJZBIKCgJlcRgBIAMoCRIOCgZub3RfZXEYAiADKAkaQgoETmFtZRIKCgJlcRgBIAMoCRIOCgZub3RfZXEYAiADKAkSDAoEbGlrZRgDIAMoCRIQCghub3RfbGlrZRgEIAMoCRpsCgtEZXNjcmlwdGlvbhIPCgdpc19udWxsGAEgASgIEhAKCG5vdF9udWxsGAIgASgIEgoKAmVxGAMgAygJEg4KBm5vdF9lcRgEIAMoCRIMCgRsaWtlGAUgAygJEhAKCG5vdF9saWtlGAYgAygJIj0KFlRhZ1RyYW5zbGF0aW9uU2NoZW1hSUQSDgoGdGFnX2lkGAEgASgJEhMKC2xhbmd1YWdlX2lkGAIgASgJKscBChlUYWdUcmFuc2xhdGlvblNjaGVtYUZpZWxkEicKI1RBR19UUkFOU0xBVElPTl9TQ0hFTUFfRklFTERfVEFHX0lEEAASLAooVEFHX1RSQU5TTEFUSU9OX1NDSEVNQV9GSUVMRF9MQU5HVUFHRV9JRBABEiUKIVRBR19UUkFOU0xBVElPTl9TQ0hFTUFfRklFTERfTkFNRRACEiwKKFRBR19UUkFOU0xBVElPTl9TQ0hFTUFfRklFTERfREVTQ1JJUFRJT04QA0IzWh5hYmxpYnJhcnkubmV0L2FwaS9wcm90by9zY2hlbWGqAhBBQkxpYnJhcnkuU2NoZW1hYghlZGl0aW9uc3DoBw", [file_ablibrary_types_common]);

/**
 * @generated from message ablibrary.schema.TagTranslationSchema
 */
export type TagTranslationSchema = Message<"ablibrary.schema.TagTranslationSchema"> & {
  /**
   * @generated from field: string tag_id = 1;
   */
  tagId: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;
};

/**
 * @generated from message ablibrary.schema.TagTranslationSchema
 */
export type TagTranslationSchemaJson = {
  /**
   * @generated from field: string tag_id = 1;
   */
  tagId?: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId?: string;

  /**
   * @generated from field: string name = 3;
   */
  name?: string;

  /**
   * @generated from field: string description = 4;
   */
  description?: string;
};

/**
 * Describes the message ablibrary.schema.TagTranslationSchema.
 * Use `create(TagTranslationSchemaSchema)` to create a new message.
 */
export const TagTranslationSchemaSchema: GenMessage<TagTranslationSchema, {jsonType: TagTranslationSchemaJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_translation_schema, 0);

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters
 */
export type TagTranslationSchemaFilters = Message<"ablibrary.schema.TagTranslationSchemaFilters"> & {
  /**
   * @generated from field: repeated ablibrary.schema.TagTranslationSchemaFilters.TagId tag_id = 1;
   */
  tagId: TagTranslationSchemaFilters_TagId[];

  /**
   * @generated from field: repeated ablibrary.schema.TagTranslationSchemaFilters.LanguageId language_id = 2;
   */
  languageId: TagTranslationSchemaFilters_LanguageId[];

  /**
   * @generated from field: repeated ablibrary.schema.TagTranslationSchemaFilters.Name name = 3;
   */
  name: TagTranslationSchemaFilters_Name[];

  /**
   * @generated from field: repeated ablibrary.schema.TagTranslationSchemaFilters.Description description = 4;
   */
  description: TagTranslationSchemaFilters_Description[];
};

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters
 */
export type TagTranslationSchemaFiltersJson = {
  /**
   * @generated from field: repeated ablibrary.schema.TagTranslationSchemaFilters.TagId tag_id = 1;
   */
  tagId?: TagTranslationSchemaFilters_TagIdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.TagTranslationSchemaFilters.LanguageId language_id = 2;
   */
  languageId?: TagTranslationSchemaFilters_LanguageIdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.TagTranslationSchemaFilters.Name name = 3;
   */
  name?: TagTranslationSchemaFilters_NameJson[];

  /**
   * @generated from field: repeated ablibrary.schema.TagTranslationSchemaFilters.Description description = 4;
   */
  description?: TagTranslationSchemaFilters_DescriptionJson[];
};

/**
 * Describes the message ablibrary.schema.TagTranslationSchemaFilters.
 * Use `create(TagTranslationSchemaFiltersSchema)` to create a new message.
 */
export const TagTranslationSchemaFiltersSchema: GenMessage<TagTranslationSchemaFilters, {jsonType: TagTranslationSchemaFiltersJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_translation_schema, 1);

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters.TagId
 */
export type TagTranslationSchemaFilters_TagId = Message<"ablibrary.schema.TagTranslationSchemaFilters.TagId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters.TagId
 */
export type TagTranslationSchemaFilters_TagIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.TagTranslationSchemaFilters.TagId.
 * Use `create(TagTranslationSchemaFilters_TagIdSchema)` to create a new message.
 */
export const TagTranslationSchemaFilters_TagIdSchema: GenMessage<TagTranslationSchemaFilters_TagId, {jsonType: TagTranslationSchemaFilters_TagIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_translation_schema, 1, 0);

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters.LanguageId
 */
export type TagTranslationSchemaFilters_LanguageId = Message<"ablibrary.schema.TagTranslationSchemaFilters.LanguageId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters.LanguageId
 */
export type TagTranslationSchemaFilters_LanguageIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.TagTranslationSchemaFilters.LanguageId.
 * Use `create(TagTranslationSchemaFilters_LanguageIdSchema)` to create a new message.
 */
export const TagTranslationSchemaFilters_LanguageIdSchema: GenMessage<TagTranslationSchemaFilters_LanguageId, {jsonType: TagTranslationSchemaFilters_LanguageIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_translation_schema, 1, 1);

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters.Name
 */
export type TagTranslationSchemaFilters_Name = Message<"ablibrary.schema.TagTranslationSchemaFilters.Name"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];

  /**
   * @generated from field: repeated string like = 3;
   */
  like: string[];

  /**
   * @generated from field: repeated string not_like = 4;
   */
  notLike: string[];
};

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters.Name
 */
export type TagTranslationSchemaFilters_NameJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];

  /**
   * @generated from field: repeated string like = 3;
   */
  like?: string[];

  /**
   * @generated from field: repeated string not_like = 4;
   */
  notLike?: string[];
};

/**
 * Describes the message ablibrary.schema.TagTranslationSchemaFilters.Name.
 * Use `create(TagTranslationSchemaFilters_NameSchema)` to create a new message.
 */
export const TagTranslationSchemaFilters_NameSchema: GenMessage<TagTranslationSchemaFilters_Name, {jsonType: TagTranslationSchemaFilters_NameJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_translation_schema, 1, 2);

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters.Description
 */
export type TagTranslationSchemaFilters_Description = Message<"ablibrary.schema.TagTranslationSchemaFilters.Description"> & {
  /**
   * @generated from field: bool is_null = 1;
   */
  isNull: boolean;

  /**
   * @generated from field: bool not_null = 2;
   */
  notNull: boolean;

  /**
   * @generated from field: repeated string eq = 3;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 4;
   */
  notEq: string[];

  /**
   * @generated from field: repeated string like = 5;
   */
  like: string[];

  /**
   * @generated from field: repeated string not_like = 6;
   */
  notLike: string[];
};

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaFilters.Description
 */
export type TagTranslationSchemaFilters_DescriptionJson = {
  /**
   * @generated from field: bool is_null = 1;
   */
  isNull?: boolean;

  /**
   * @generated from field: bool not_null = 2;
   */
  notNull?: boolean;

  /**
   * @generated from field: repeated string eq = 3;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 4;
   */
  notEq?: string[];

  /**
   * @generated from field: repeated string like = 5;
   */
  like?: string[];

  /**
   * @generated from field: repeated string not_like = 6;
   */
  notLike?: string[];
};

/**
 * Describes the message ablibrary.schema.TagTranslationSchemaFilters.Description.
 * Use `create(TagTranslationSchemaFilters_DescriptionSchema)` to create a new message.
 */
export const TagTranslationSchemaFilters_DescriptionSchema: GenMessage<TagTranslationSchemaFilters_Description, {jsonType: TagTranslationSchemaFilters_DescriptionJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_translation_schema, 1, 3);

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaID
 */
export type TagTranslationSchemaID = Message<"ablibrary.schema.TagTranslationSchemaID"> & {
  /**
   * @generated from field: string tag_id = 1;
   */
  tagId: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId: string;
};

/**
 * @generated from message ablibrary.schema.TagTranslationSchemaID
 */
export type TagTranslationSchemaIDJson = {
  /**
   * @generated from field: string tag_id = 1;
   */
  tagId?: string;

  /**
   * @generated from field: string language_id = 2;
   */
  languageId?: string;
};

/**
 * Describes the message ablibrary.schema.TagTranslationSchemaID.
 * Use `create(TagTranslationSchemaIDSchema)` to create a new message.
 */
export const TagTranslationSchemaIDSchema: GenMessage<TagTranslationSchemaID, {jsonType: TagTranslationSchemaIDJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_tag_translation_schema, 2);

/**
 * @generated from enum ablibrary.schema.TagTranslationSchemaField
 */
export enum TagTranslationSchemaField {
  /**
   * @generated from enum value: TAG_TRANSLATION_SCHEMA_FIELD_TAG_ID = 0;
   */
  TAG_ID = 0,

  /**
   * @generated from enum value: TAG_TRANSLATION_SCHEMA_FIELD_LANGUAGE_ID = 1;
   */
  LANGUAGE_ID = 1,

  /**
   * @generated from enum value: TAG_TRANSLATION_SCHEMA_FIELD_NAME = 2;
   */
  NAME = 2,

  /**
   * @generated from enum value: TAG_TRANSLATION_SCHEMA_FIELD_DESCRIPTION = 3;
   */
  DESCRIPTION = 3,
}

/**
 * @generated from enum ablibrary.schema.TagTranslationSchemaField
 */
export type TagTranslationSchemaFieldJson = "TAG_TRANSLATION_SCHEMA_FIELD_TAG_ID" | "TAG_TRANSLATION_SCHEMA_FIELD_LANGUAGE_ID" | "TAG_TRANSLATION_SCHEMA_FIELD_NAME" | "TAG_TRANSLATION_SCHEMA_FIELD_DESCRIPTION";

/**
 * Describes the enum ablibrary.schema.TagTranslationSchemaField.
 */
export const TagTranslationSchemaFieldSchema: GenEnum<TagTranslationSchemaField, TagTranslationSchemaFieldJson> = /*@__PURE__*/
  enumDesc(file_ablibrary_schema_tag_translation_schema, 0);

