// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file ablibrary/schema/user_permission_schema.proto (package ablibrary.schema, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_ablibrary_types_common } from "../types/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ablibrary/schema/user_permission_schema.proto.
 */
export const file_ablibrary_schema_user_permission_schema: GenFile = /*@__PURE__*/
  fileDesc("Ci1hYmxpYnJhcnkvc2NoZW1hL3VzZXJfcGVybWlzc2lvbl9zY2hlbWEucHJvdG8SEGFibGlicmFyeS5zY2hlbWEiPgoUVXNlclBlcm1pc3Npb25TY2hlbWESDwoHdXNlcl9pZBgBIAEoCRIVCg1wZXJtaXNzaW9uX2lkGAIgASgJIokCChtVc2VyUGVybWlzc2lvblNjaGVtYUZpbHRlcnMSRQoHdXNlcl9pZBgBIAMoCzI0LmFibGlicmFyeS5zY2hlbWEuVXNlclBlcm1pc3Npb25TY2hlbWFGaWx0ZXJzLlVzZXJJZBJRCg1wZXJtaXNzaW9uX2lkGAIgAygLMjouYWJsaWJyYXJ5LnNjaGVtYS5Vc2VyUGVybWlzc2lvblNjaGVtYUZpbHRlcnMuUGVybWlzc2lvbklkGiQKBlVzZXJJZBIKCgJlcRgBIAMoCRIOCgZub3RfZXEYAiADKAkaKgoMUGVybWlzc2lvbklkEgoKAmVxGAEgAygJEg4KBm5vdF9lcRgCIAMoCSJAChZVc2VyUGVybWlzc2lvblNjaGVtYUlEEg8KB3VzZXJfaWQYASABKAkSFQoNcGVybWlzc2lvbl9pZBgCIAEoCSp1ChlVc2VyUGVybWlzc2lvblNjaGVtYUZpZWxkEigKJFVTRVJfUEVSTUlTU0lPTl9TQ0hFTUFfRklFTERfVVNFUl9JRBAAEi4KKlVTRVJfUEVSTUlTU0lPTl9TQ0hFTUFfRklFTERfUEVSTUlTU0lPTl9JRBABQjNaHmFibGlicmFyeS5uZXQvYXBpL3Byb3RvL3NjaGVtYaoCEEFCTGlicmFyeS5TY2hlbWFiCGVkaXRpb25zcOgH", [file_ablibrary_types_common]);

/**
 * @generated from message ablibrary.schema.UserPermissionSchema
 */
export type UserPermissionSchema = Message<"ablibrary.schema.UserPermissionSchema"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string permission_id = 2;
   */
  permissionId: string;
};

/**
 * @generated from message ablibrary.schema.UserPermissionSchema
 */
export type UserPermissionSchemaJson = {
  /**
   * @generated from field: string user_id = 1;
   */
  userId?: string;

  /**
   * @generated from field: string permission_id = 2;
   */
  permissionId?: string;
};

/**
 * Describes the message ablibrary.schema.UserPermissionSchema.
 * Use `create(UserPermissionSchemaSchema)` to create a new message.
 */
export const UserPermissionSchemaSchema: GenMessage<UserPermissionSchema, {jsonType: UserPermissionSchemaJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_user_permission_schema, 0);

/**
 * @generated from message ablibrary.schema.UserPermissionSchemaFilters
 */
export type UserPermissionSchemaFilters = Message<"ablibrary.schema.UserPermissionSchemaFilters"> & {
  /**
   * @generated from field: repeated ablibrary.schema.UserPermissionSchemaFilters.UserId user_id = 1;
   */
  userId: UserPermissionSchemaFilters_UserId[];

  /**
   * @generated from field: repeated ablibrary.schema.UserPermissionSchemaFilters.PermissionId permission_id = 2;
   */
  permissionId: UserPermissionSchemaFilters_PermissionId[];
};

/**
 * @generated from message ablibrary.schema.UserPermissionSchemaFilters
 */
export type UserPermissionSchemaFiltersJson = {
  /**
   * @generated from field: repeated ablibrary.schema.UserPermissionSchemaFilters.UserId user_id = 1;
   */
  userId?: UserPermissionSchemaFilters_UserIdJson[];

  /**
   * @generated from field: repeated ablibrary.schema.UserPermissionSchemaFilters.PermissionId permission_id = 2;
   */
  permissionId?: UserPermissionSchemaFilters_PermissionIdJson[];
};

/**
 * Describes the message ablibrary.schema.UserPermissionSchemaFilters.
 * Use `create(UserPermissionSchemaFiltersSchema)` to create a new message.
 */
export const UserPermissionSchemaFiltersSchema: GenMessage<UserPermissionSchemaFilters, {jsonType: UserPermissionSchemaFiltersJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_user_permission_schema, 1);

/**
 * @generated from message ablibrary.schema.UserPermissionSchemaFilters.UserId
 */
export type UserPermissionSchemaFilters_UserId = Message<"ablibrary.schema.UserPermissionSchemaFilters.UserId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.UserPermissionSchemaFilters.UserId
 */
export type UserPermissionSchemaFilters_UserIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.UserPermissionSchemaFilters.UserId.
 * Use `create(UserPermissionSchemaFilters_UserIdSchema)` to create a new message.
 */
export const UserPermissionSchemaFilters_UserIdSchema: GenMessage<UserPermissionSchemaFilters_UserId, {jsonType: UserPermissionSchemaFilters_UserIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_user_permission_schema, 1, 0);

/**
 * @generated from message ablibrary.schema.UserPermissionSchemaFilters.PermissionId
 */
export type UserPermissionSchemaFilters_PermissionId = Message<"ablibrary.schema.UserPermissionSchemaFilters.PermissionId"> & {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq: string[];
};

/**
 * @generated from message ablibrary.schema.UserPermissionSchemaFilters.PermissionId
 */
export type UserPermissionSchemaFilters_PermissionIdJson = {
  /**
   * @generated from field: repeated string eq = 1;
   */
  eq?: string[];

  /**
   * @generated from field: repeated string not_eq = 2;
   */
  notEq?: string[];
};

/**
 * Describes the message ablibrary.schema.UserPermissionSchemaFilters.PermissionId.
 * Use `create(UserPermissionSchemaFilters_PermissionIdSchema)` to create a new message.
 */
export const UserPermissionSchemaFilters_PermissionIdSchema: GenMessage<UserPermissionSchemaFilters_PermissionId, {jsonType: UserPermissionSchemaFilters_PermissionIdJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_user_permission_schema, 1, 1);

/**
 * @generated from message ablibrary.schema.UserPermissionSchemaID
 */
export type UserPermissionSchemaID = Message<"ablibrary.schema.UserPermissionSchemaID"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string permission_id = 2;
   */
  permissionId: string;
};

/**
 * @generated from message ablibrary.schema.UserPermissionSchemaID
 */
export type UserPermissionSchemaIDJson = {
  /**
   * @generated from field: string user_id = 1;
   */
  userId?: string;

  /**
   * @generated from field: string permission_id = 2;
   */
  permissionId?: string;
};

/**
 * Describes the message ablibrary.schema.UserPermissionSchemaID.
 * Use `create(UserPermissionSchemaIDSchema)` to create a new message.
 */
export const UserPermissionSchemaIDSchema: GenMessage<UserPermissionSchemaID, {jsonType: UserPermissionSchemaIDJson}> = /*@__PURE__*/
  messageDesc(file_ablibrary_schema_user_permission_schema, 2);

/**
 * @generated from enum ablibrary.schema.UserPermissionSchemaField
 */
export enum UserPermissionSchemaField {
  /**
   * @generated from enum value: USER_PERMISSION_SCHEMA_FIELD_USER_ID = 0;
   */
  USER_ID = 0,

  /**
   * @generated from enum value: USER_PERMISSION_SCHEMA_FIELD_PERMISSION_ID = 1;
   */
  PERMISSION_ID = 1,
}

/**
 * @generated from enum ablibrary.schema.UserPermissionSchemaField
 */
export type UserPermissionSchemaFieldJson = "USER_PERMISSION_SCHEMA_FIELD_USER_ID" | "USER_PERMISSION_SCHEMA_FIELD_PERMISSION_ID";

/**
 * Describes the enum ablibrary.schema.UserPermissionSchemaField.
 */
export const UserPermissionSchemaFieldSchema: GenEnum<UserPermissionSchemaField, UserPermissionSchemaFieldJson> = /*@__PURE__*/
  enumDesc(file_ablibrary_schema_user_permission_schema, 0);

