export const PATHS = {
  HOME: "/",
  ARTICLES: "/articles",
  ARTICLE: (articleSlug: string) => `/articles/${articleSlug}`,
  IMAGES: "/images",
  IMAGE: (imageId: string) => `/images/${imageId}`,
  DOCUMENTS: "/documents",
  DOCUMENT: (documentId: string) => `/documents/${documentId}`,
  PLAYLISTS: "/videos",
  PLAYLIST: (videoId: string) => `/videos/${videoId}`,
  AUDIOS: "/audios",
  AUDIO: (audioId: string) => `/audios/${audioId}`,
  BOOKS: "/books",
  BOOK: (bookSlug: string) => `/books/${bookSlug}`,
  BIOGRAPHY: "/biography",
  ABOUT_US: "/about-us",
  CONTACT_US: "/contact-us",
  PUBLISH_LICENSE: "/publish-license",
};
