// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/types/abx_tag.proto (package ablibrary.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Metadata } from "./metadata_pb";

/**
 * @generated from message ablibrary.types.ABXTag
 */
export declare class ABXTag extends Message<ABXTag> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string label = 2;
   */
  label?: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * @generated from field: string opening_tag = 4;
   */
  openingTag: string;

  /**
   * @generated from field: optional string closing_tag = 5;
   */
  closingTag?: string;

  /**
   * @generated from field: bool is_self_closing = 6;
   */
  isSelfClosing: boolean;

  /**
   * @generated from field: repeated ablibrary.types.ABXTag allowed_children = 7;
   */
  allowedChildren: ABXTag[];

  /**
   * @generated from field: repeated ablibrary.types.ABXAttribute allowed_attributes = 8;
   */
  allowedAttributes: ABXAttribute[];

  /**
   * @generated from field: optional int32 version = 9;
   */
  version?: number;

  /**
   * @generated from field: optional ablibrary.types.Metadata metadata = 10;
   */
  metadata?: Metadata;

  constructor(data?: PartialMessage<ABXTag>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.types.ABXTag";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ABXTag;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ABXTag;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ABXTag;

  static equals(a: ABXTag | PlainMessage<ABXTag> | undefined, b: ABXTag | PlainMessage<ABXTag> | undefined): boolean;
}

/**
 * @generated from message ablibrary.types.ABXAttribute
 */
export declare class ABXAttribute extends Message<ABXAttribute> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Pattern is an optional regular expression used for validating attribute value.
   * For example "09\d {9}" can be used to validate mobile number, shuch as 09123456789.
   *
   * @generated from field: optional string pattern = 3;
   */
  pattern?: string;

  /**
   * @generated from field: optional string label = 4;
   */
  label?: string;

  /**
   * @generated from field: optional string description = 5;
   */
  description?: string;

  constructor(data?: PartialMessage<ABXAttribute>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.types.ABXAttribute";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ABXAttribute;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ABXAttribute;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ABXAttribute;

  static equals(a: ABXAttribute | PlainMessage<ABXAttribute> | undefined, b: ABXAttribute | PlainMessage<ABXAttribute> | undefined): boolean;
}

