// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/types/country.proto (package ablibrary.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Metadata } from "./metadata_pb";

/**
 * @generated from message ablibrary.types.Country
 */
export declare class Country extends Message<Country> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional ablibrary.types.Metadata metadata = 3;
   */
  metadata?: Metadata;

  constructor(data?: PartialMessage<Country>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.types.Country";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Country;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Country;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Country;

  static equals(a: Country | PlainMessage<Country> | undefined, b: Country | PlainMessage<Country> | undefined): boolean;
}

