// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/types/field_mask.proto (package ablibrary.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, FieldMask as FieldMask$1, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum ablibrary.types.FieldMaskTemplate
 */
export declare enum FieldMaskTemplate {
  /**
   * @generated from enum value: FIELD_MASK_TEMPLATE_FULL = 0;
   */
  FULL = 0,

  /**
   * @generated from enum value: FIELD_MASK_TEMPLATE_BASIC = 1;
   */
  BASIC = 1,

  /**
   * @generated from enum value: FIELD_MASK_TEMPLATE_ID = 2;
   */
  ID = 2,

  /**
   * @generated from enum value: FIELD_MASK_TEMPLATE_ID_LABEL = 3;
   */
  ID_LABEL = 3,
}

/**
 * @generated from message ablibrary.types.FieldMask
 */
export declare class FieldMask extends Message<FieldMask> {
  /**
   * @generated from field: optional google.protobuf.FieldMask only = 1;
   */
  only?: FieldMask$1;

  /**
   * @generated from field: optional google.protobuf.FieldMask except = 2;
   */
  except?: FieldMask$1;

  /**
   * @generated from field: optional ablibrary.types.FieldMaskTemplate template = 3;
   */
  template?: FieldMaskTemplate;

  /**
   * @generated from field: optional int32 max_depth = 4;
   */
  maxDepth?: number;

  constructor(data?: PartialMessage<FieldMask>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.types.FieldMask";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FieldMask;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FieldMask;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FieldMask;

  static equals(a: FieldMask | PlainMessage<FieldMask> | undefined, b: FieldMask | PlainMessage<FieldMask> | undefined): boolean;
}

