// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/types/file.proto (package ablibrary.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Metadata } from "./metadata_pb";

/**
 * @generated from message ablibrary.types.File
 */
export class File extends Message<File> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: optional string filename = 2;
   */
  filename?: string;

  /**
   * @generated from field: optional string mimetype = 3;
   */
  mimetype?: string;

  /**
   * @generated from field: optional uint64 size = 4;
   */
  size?: bigint;

  /**
   * @generated from field: optional string url = 5;
   */
  url?: string;

  /**
   * @generated from field: optional string hash = 6;
   */
  hash?: string;

  /**
   * @generated from field: optional ablibrary.types.Metadata metadata = 7;
   */
  metadata?: Metadata;

  constructor(data?: PartialMessage<File>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.File";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "mimetype", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "size", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 5, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "hash", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "metadata", kind: "message", T: Metadata, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): File {
    return new File().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): File {
    return new File().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): File {
    return new File().fromJsonString(jsonString, options);
  }

  static equals(a: File | PlainMessage<File> | undefined, b: File | PlainMessage<File> | undefined): boolean {
    return proto3.util.equals(File, a, b);
  }
}

