// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/types/localized_string.proto (package ablibrary.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Metadata } from "./metadata_pb";

/**
 * @generated from message ablibrary.types.LocalizedString
 */
export declare class LocalizedString extends Message<LocalizedString> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * @generated from field: optional string category = 3;
   */
  category?: string;

  /**
   * @generated from field: repeated string parameters = 4;
   */
  parameters: string[];

  /**
   * @generated from field: optional string description = 5;
   */
  description?: string;

  /**
   * maps language id to translation
   *
   * @generated from field: map<string, string> translations = 6;
   */
  translations: { [key: string]: string };

  /**
   * @generated from field: optional ablibrary.types.Metadata metadata = 7;
   */
  metadata?: Metadata;

  constructor(data?: PartialMessage<LocalizedString>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.types.LocalizedString";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocalizedString;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocalizedString;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocalizedString;

  static equals(a: LocalizedString | PlainMessage<LocalizedString> | undefined, b: LocalizedString | PlainMessage<LocalizedString> | undefined): boolean;
}

