// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/types/metadata.proto (package ablibrary.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { User } from "./user_pb";
import type { DateTime } from "./common_pb";

/**
 * @generated from enum ablibrary.types.DataState
 */
export declare enum DataState {
  /**
   * @generated from enum value: DATA_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DATA_STATE_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * @generated from enum value: DATA_STATE_PENDING_APPROVAL = 2;
   */
  PENDING_APPROVAL = 2,

  /**
   * @generated from enum value: DATA_STATE_READY_TO_PUBLISH = 3;
   */
  READY_TO_PUBLISH = 3,

  /**
   * @generated from enum value: DATA_STATE_PUBLISHED = 4;
   */
  PUBLISHED = 4,

  /**
   * @generated from enum value: DATA_STATE_VERIFIED = 5;
   */
  VERIFIED = 5,

  /**
   * @generated from enum value: DATA_STATE_REJECTED = 6;
   */
  REJECTED = 6,

  /**
   * @generated from enum value: DATA_STATE_DELETED = 7;
   */
  DELETED = 7,
}

/**
 * @generated from enum ablibrary.types.DataLocality
 */
export declare enum DataLocality {
  /**
   * @generated from enum value: DATA_LOCALITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DATA_LOCALITY_LOCAL = 1;
   */
  LOCAL = 1,

  /**
   * @generated from enum value: DATA_LOCALITY_REMOTE = 2;
   */
  REMOTE = 2,

  /**
   * @generated from enum value: DATA_LOCALITY_GLOBAL = 3;
   */
  GLOBAL = 3,
}

/**
 * @generated from enum ablibrary.types.DataOwnership
 */
export declare enum DataOwnership {
  /**
   * @generated from enum value: DATA_OWNERSHIP_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DATA_OWNERSHIP_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: DATA_OWNERSHIP_ABLIBRARY = 2;
   */
  ABLIBRARY = 2,

  /**
   * @generated from enum value: DATA_OWNERSHIP_SHARED = 3;
   */
  SHARED = 3,

  /**
   * @generated from enum value: DATA_OWNERSHIP_PUBLIC = 4;
   */
  PUBLIC = 4,

  /**
   * @generated from enum value: DATA_OWNERSHIP_MISC = 5;
   */
  MISC = 5,
}

/**
 * @generated from enum ablibrary.types.DataVisibilityScope
 */
export declare enum DataVisibilityScope {
  /**
   * @generated from enum value: DATA_VISIBILITY_SCOPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DATA_VISIBILITY_SCOPE_PUBLIC = 1;
   */
  PUBLIC = 1,

  /**
   * @generated from enum value: DATA_VISIBILITY_SCOPE_PRIVATE = 2;
   */
  PRIVATE = 2,

  /**
   * @generated from enum value: DATA_VISIBILITY_SCOPE_SHARED = 3;
   */
  SHARED = 3,
}

/**
 * @generated from message ablibrary.types.Metadata
 */
export declare class Metadata extends Message<Metadata> {
  /**
   * @generated from field: optional string revision_id = 1;
   */
  revisionId?: string;

  /**
   * @generated from field: optional ablibrary.types.User user = 2;
   */
  user?: User;

  /**
   * @generated from field: optional ablibrary.types.Status status = 3;
   */
  status?: Status;

  /**
   * @generated from field: optional ablibrary.types.DateTime created_at = 4;
   */
  createdAt?: DateTime;

  /**
   * @generated from field: optional ablibrary.types.DateTime updated_at = 5;
   */
  updatedAt?: DateTime;

  /**
   * @generated from field: optional ablibrary.types.DataOwnership data_ownership = 6;
   */
  dataOwnership?: DataOwnership;

  /**
   * @generated from field: optional ablibrary.types.DataVisibilityScope data_scope = 7;
   */
  dataScope?: DataVisibilityScope;

  /**
   * @generated from field: optional ablibrary.types.DataLocality data_locality = 8;
   */
  dataLocality?: DataLocality;

  constructor(data?: PartialMessage<Metadata>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.types.Metadata";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Metadata;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Metadata;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Metadata;

  static equals(a: Metadata | PlainMessage<Metadata> | undefined, b: Metadata | PlainMessage<Metadata> | undefined): boolean;
}

/**
 * @generated from message ablibrary.types.Status
 */
export declare class Status extends Message<Status> {
  /**
   * @generated from field: ablibrary.types.DataState status = 1;
   */
  status: DataState;

  /**
   * @generated from field: optional string label = 2;
   */
  label?: string;

  /**
   * @generated from field: optional ablibrary.types.DateTime updated_at = 3;
   */
  updatedAt?: DateTime;

  /**
   * @generated from field: optional string reason = 4;
   */
  reason?: string;

  constructor(data?: PartialMessage<Status>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.types.Status";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Status;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Status;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Status;

  static equals(a: Status | PlainMessage<Status> | undefined, b: Status | PlainMessage<Status> | undefined): boolean;
}

