// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/types/page_content.proto (package ablibrary.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum ablibrary.types.PageContentReferenceKind
 */
export enum PageContentReferenceKind {
  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_HTTP = 1;
   */
  HTTP = 1,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_BOOK = 2;
   */
  BOOK = 2,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_PAGE = 3;
   */
  PAGE = 3,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_CONTENT = 4;
   */
  CONTENT = 4,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_PUBLISHER = 5;
   */
  PUBLISHER = 5,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_CONTRIBUTOR = 6;
   */
  CONTRIBUTOR = 6,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_CONTRIBUTION = 7;
   */
  CONTRIBUTION = 7,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_QURANVERSE = 8;
   */
  QURANVERSE = 8,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_QUESTION = 9;
   */
  QUESTION = 9,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_DICTIONARY = 10;
   */
  DICTIONARY = 10,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_BIBLIOGRAPHY = 11;
   */
  BIBLIOGRAPHY = 11,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_NARRATOR = 12;
   */
  NARRATOR = 12,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_GENEALOGY = 13;
   */
  GENEALOGY = 13,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_TERM = 14;
   */
  TERM = 14,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_CELEBRITY = 15;
   */
  CELEBRITY = 15,

  /**
   * @generated from enum value: PAGE_CONTENT_REFERENCE_KIND_EXEGESIS = 16;
   */
  EXEGESIS = 16,
}
// Retrieve enum metadata with: proto3.getEnumType(PageContentReferenceKind)
proto3.util.setEnumType(PageContentReferenceKind, "ablibrary.types.PageContentReferenceKind", [
  { no: 0, name: "PAGE_CONTENT_REFERENCE_KIND_UNSPECIFIED" },
  { no: 1, name: "PAGE_CONTENT_REFERENCE_KIND_HTTP" },
  { no: 2, name: "PAGE_CONTENT_REFERENCE_KIND_BOOK" },
  { no: 3, name: "PAGE_CONTENT_REFERENCE_KIND_PAGE" },
  { no: 4, name: "PAGE_CONTENT_REFERENCE_KIND_CONTENT" },
  { no: 5, name: "PAGE_CONTENT_REFERENCE_KIND_PUBLISHER" },
  { no: 6, name: "PAGE_CONTENT_REFERENCE_KIND_CONTRIBUTOR" },
  { no: 7, name: "PAGE_CONTENT_REFERENCE_KIND_CONTRIBUTION" },
  { no: 8, name: "PAGE_CONTENT_REFERENCE_KIND_QURANVERSE" },
  { no: 9, name: "PAGE_CONTENT_REFERENCE_KIND_QUESTION" },
  { no: 10, name: "PAGE_CONTENT_REFERENCE_KIND_DICTIONARY" },
  { no: 11, name: "PAGE_CONTENT_REFERENCE_KIND_BIBLIOGRAPHY" },
  { no: 12, name: "PAGE_CONTENT_REFERENCE_KIND_NARRATOR" },
  { no: 13, name: "PAGE_CONTENT_REFERENCE_KIND_GENEALOGY" },
  { no: 14, name: "PAGE_CONTENT_REFERENCE_KIND_TERM" },
  { no: 15, name: "PAGE_CONTENT_REFERENCE_KIND_CELEBRITY" },
  { no: 16, name: "PAGE_CONTENT_REFERENCE_KIND_EXEGESIS" },
]);

/**
 * @generated from message ablibrary.types.PageContent
 */
export class PageContent extends Message<PageContent> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string book_id = 2;
   */
  bookId = "";

  /**
   * @generated from field: optional string parent_id = 3;
   */
  parentId?: string;

  /**
   * @generated from field: optional string language_id = 4;
   */
  languageId?: string;

  /**
   * @generated from field: optional string page_id = 5;
   */
  pageId?: string;

  /**
   * @generated from field: optional int32 page_number = 6;
   */
  pageNumber?: number;

  /**
   * @generated from field: optional int32 weight = 7;
   */
  weight?: number;

  /**
   * @generated from field: map<string, string> style = 8;
   */
  style: { [key: string]: string } = {};

  /**
   * @generated from field: map<string, string> attributes = 9;
   */
  attributes: { [key: string]: string } = {};

  /**
   * @generated from field: repeated ablibrary.types.PageContent children = 10;
   */
  children: PageContent[] = [];

  /**
   * @generated from oneof ablibrary.types.PageContent.data
   */
  data: {
    /**
     * @generated from field: ablibrary.types.PageContentFootnote footnote = 11;
     */
    value: PageContentFootnote;
    case: "footnote";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentHeading heading = 12;
     */
    value: PageContentHeading;
    case: "heading";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentHighlight highlight = 13;
     */
    value: PageContentHighlight;
    case: "highlight";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentHorizontalLine horizontal_line = 14;
     */
    value: PageContentHorizontalLine;
    case: "horizontalLine";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentImage image = 15;
     */
    value: PageContentImage;
    case: "image";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentLineBreak line_break = 16;
     */
    value: PageContentLineBreak;
    case: "lineBreak";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentParagraph paragraph = 17;
     */
    value: PageContentParagraph;
    case: "paragraph";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentPoem poem = 18;
     */
    value: PageContentPoem;
    case: "poem";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentReference ref = 19;
     */
    value: PageContentReference;
    case: "ref";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentRemark remark = 20;
     */
    value: PageContentRemark;
    case: "remark";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentTable table = 21;
     */
    value: PageContentTable;
    case: "table";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentTableCell table_cell = 22;
     */
    value: PageContentTableCell;
    case: "tableCell";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentTableRow table_row = 23;
     */
    value: PageContentTableRow;
    case: "tableRow";
  } | {
    /**
     * @generated from field: ablibrary.types.PageContentText text = 24;
     */
    value: PageContentText;
    case: "text";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<PageContent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "book_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "parent_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "language_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "page_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "page_number", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 7, name: "weight", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 8, name: "style", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 9, name: "attributes", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 10, name: "children", kind: "message", T: PageContent, repeated: true },
    { no: 11, name: "footnote", kind: "message", T: PageContentFootnote, oneof: "data" },
    { no: 12, name: "heading", kind: "message", T: PageContentHeading, oneof: "data" },
    { no: 13, name: "highlight", kind: "message", T: PageContentHighlight, oneof: "data" },
    { no: 14, name: "horizontal_line", kind: "message", T: PageContentHorizontalLine, oneof: "data" },
    { no: 15, name: "image", kind: "message", T: PageContentImage, oneof: "data" },
    { no: 16, name: "line_break", kind: "message", T: PageContentLineBreak, oneof: "data" },
    { no: 17, name: "paragraph", kind: "message", T: PageContentParagraph, oneof: "data" },
    { no: 18, name: "poem", kind: "message", T: PageContentPoem, oneof: "data" },
    { no: 19, name: "ref", kind: "message", T: PageContentReference, oneof: "data" },
    { no: 20, name: "remark", kind: "message", T: PageContentRemark, oneof: "data" },
    { no: 21, name: "table", kind: "message", T: PageContentTable, oneof: "data" },
    { no: 22, name: "table_cell", kind: "message", T: PageContentTableCell, oneof: "data" },
    { no: 23, name: "table_row", kind: "message", T: PageContentTableRow, oneof: "data" },
    { no: 24, name: "text", kind: "message", T: PageContentText, oneof: "data" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContent {
    return new PageContent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContent {
    return new PageContent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContent {
    return new PageContent().fromJsonString(jsonString, options);
  }

  static equals(a: PageContent | PlainMessage<PageContent> | undefined, b: PageContent | PlainMessage<PageContent> | undefined): boolean {
    return proto3.util.equals(PageContent, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentRef
 */
export class PageContentRef extends Message<PageContentRef> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string book_id = 2;
   */
  bookId = "";

  /**
   * @generated from field: string page_id = 3;
   */
  pageId = "";

  /**
   * @generated from field: optional string content_id = 4;
   */
  contentId?: string;

  /**
   * @generated from field: optional string parent_id = 5;
   */
  parentId?: string;

  /**
   * @generated from field: string title = 6;
   */
  title = "";

  /**
   * @generated from field: int32 page_number = 7;
   */
  pageNumber = 0;

  /**
   * @generated from field: optional string page_label = 8;
   */
  pageLabel?: string;

  /**
   * @generated from field: optional int32 source_page_number = 9;
   */
  sourcePageNumber?: number;

  /**
   * @generated from field: optional string source_page_label = 10;
   */
  sourcePageLabel?: string;

  /**
   * @generated from field: optional int32 weight = 11;
   */
  weight?: number;

  /**
   * @generated from field: optional ablibrary.types.PageContentRef parent = 12;
   */
  parent?: PageContentRef;

  /**
   * @generated from field: repeated ablibrary.types.PageContentRef children = 13;
   */
  children: PageContentRef[] = [];

  constructor(data?: PartialMessage<PageContentRef>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentRef";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "book_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "content_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "parent_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "page_number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "page_label", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "source_page_number", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 10, name: "source_page_label", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "weight", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 12, name: "parent", kind: "message", T: PageContentRef, opt: true },
    { no: 13, name: "children", kind: "message", T: PageContentRef, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentRef {
    return new PageContentRef().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentRef {
    return new PageContentRef().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentRef {
    return new PageContentRef().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentRef | PlainMessage<PageContentRef> | undefined, b: PageContentRef | PlainMessage<PageContentRef> | undefined): boolean {
    return proto3.util.equals(PageContentRef, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentText
 */
export class PageContentText extends Message<PageContentText> {
  /**
   * @generated from field: string text = 1;
   */
  text = "";

  constructor(data?: PartialMessage<PageContentText>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentText";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentText {
    return new PageContentText().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentText {
    return new PageContentText().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentText {
    return new PageContentText().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentText | PlainMessage<PageContentText> | undefined, b: PageContentText | PlainMessage<PageContentText> | undefined): boolean {
    return proto3.util.equals(PageContentText, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentParagraph
 */
export class PageContentParagraph extends Message<PageContentParagraph> {
  constructor(data?: PartialMessage<PageContentParagraph>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentParagraph";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentParagraph {
    return new PageContentParagraph().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentParagraph {
    return new PageContentParagraph().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentParagraph {
    return new PageContentParagraph().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentParagraph | PlainMessage<PageContentParagraph> | undefined, b: PageContentParagraph | PlainMessage<PageContentParagraph> | undefined): boolean {
    return proto3.util.equals(PageContentParagraph, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentFootnote
 */
export class PageContentFootnote extends Message<PageContentFootnote> {
  /**
   * @generated from field: optional string label = 1;
   */
  label?: string;

  constructor(data?: PartialMessage<PageContentFootnote>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentFootnote";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentFootnote {
    return new PageContentFootnote().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentFootnote {
    return new PageContentFootnote().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentFootnote {
    return new PageContentFootnote().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentFootnote | PlainMessage<PageContentFootnote> | undefined, b: PageContentFootnote | PlainMessage<PageContentFootnote> | undefined): boolean {
    return proto3.util.equals(PageContentFootnote, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentHeading
 */
export class PageContentHeading extends Message<PageContentHeading> {
  /**
   * @generated from field: int32 level = 1;
   */
  level = 0;

  constructor(data?: PartialMessage<PageContentHeading>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentHeading";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentHeading {
    return new PageContentHeading().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentHeading {
    return new PageContentHeading().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentHeading {
    return new PageContentHeading().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentHeading | PlainMessage<PageContentHeading> | undefined, b: PageContentHeading | PlainMessage<PageContentHeading> | undefined): boolean {
    return proto3.util.equals(PageContentHeading, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentHighlight
 */
export class PageContentHighlight extends Message<PageContentHighlight> {
  constructor(data?: PartialMessage<PageContentHighlight>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentHighlight";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentHighlight {
    return new PageContentHighlight().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentHighlight {
    return new PageContentHighlight().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentHighlight {
    return new PageContentHighlight().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentHighlight | PlainMessage<PageContentHighlight> | undefined, b: PageContentHighlight | PlainMessage<PageContentHighlight> | undefined): boolean {
    return proto3.util.equals(PageContentHighlight, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentImage
 */
export class PageContentImage extends Message<PageContentImage> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * @generated from field: optional string caption = 2;
   */
  caption?: string;

  /**
   * @generated from field: optional string alt = 3;
   */
  alt?: string;

  constructor(data?: PartialMessage<PageContentImage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentImage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "caption", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "alt", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentImage {
    return new PageContentImage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentImage {
    return new PageContentImage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentImage {
    return new PageContentImage().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentImage | PlainMessage<PageContentImage> | undefined, b: PageContentImage | PlainMessage<PageContentImage> | undefined): boolean {
    return proto3.util.equals(PageContentImage, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentTable
 */
export class PageContentTable extends Message<PageContentTable> {
  constructor(data?: PartialMessage<PageContentTable>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentTable";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentTable {
    return new PageContentTable().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentTable {
    return new PageContentTable().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentTable {
    return new PageContentTable().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentTable | PlainMessage<PageContentTable> | undefined, b: PageContentTable | PlainMessage<PageContentTable> | undefined): boolean {
    return proto3.util.equals(PageContentTable, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentTableRow
 */
export class PageContentTableRow extends Message<PageContentTableRow> {
  constructor(data?: PartialMessage<PageContentTableRow>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentTableRow";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentTableRow {
    return new PageContentTableRow().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentTableRow {
    return new PageContentTableRow().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentTableRow {
    return new PageContentTableRow().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentTableRow | PlainMessage<PageContentTableRow> | undefined, b: PageContentTableRow | PlainMessage<PageContentTableRow> | undefined): boolean {
    return proto3.util.equals(PageContentTableRow, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentTableCell
 */
export class PageContentTableCell extends Message<PageContentTableCell> {
  /**
   * @generated from field: optional int32 colspan = 1;
   */
  colspan?: number;

  /**
   * @generated from field: optional int32 rowspan = 2;
   */
  rowspan?: number;

  constructor(data?: PartialMessage<PageContentTableCell>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentTableCell";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "colspan", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 2, name: "rowspan", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentTableCell {
    return new PageContentTableCell().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentTableCell {
    return new PageContentTableCell().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentTableCell {
    return new PageContentTableCell().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentTableCell | PlainMessage<PageContentTableCell> | undefined, b: PageContentTableCell | PlainMessage<PageContentTableCell> | undefined): boolean {
    return proto3.util.equals(PageContentTableCell, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentLineBreak
 */
export class PageContentLineBreak extends Message<PageContentLineBreak> {
  constructor(data?: PartialMessage<PageContentLineBreak>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentLineBreak";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentLineBreak {
    return new PageContentLineBreak().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentLineBreak {
    return new PageContentLineBreak().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentLineBreak {
    return new PageContentLineBreak().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentLineBreak | PlainMessage<PageContentLineBreak> | undefined, b: PageContentLineBreak | PlainMessage<PageContentLineBreak> | undefined): boolean {
    return proto3.util.equals(PageContentLineBreak, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentRemark
 */
export class PageContentRemark extends Message<PageContentRemark> {
  constructor(data?: PartialMessage<PageContentRemark>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentRemark";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentRemark {
    return new PageContentRemark().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentRemark {
    return new PageContentRemark().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentRemark {
    return new PageContentRemark().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentRemark | PlainMessage<PageContentRemark> | undefined, b: PageContentRemark | PlainMessage<PageContentRemark> | undefined): boolean {
    return proto3.util.equals(PageContentRemark, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentPoem
 */
export class PageContentPoem extends Message<PageContentPoem> {
  constructor(data?: PartialMessage<PageContentPoem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentPoem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentPoem {
    return new PageContentPoem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentPoem {
    return new PageContentPoem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentPoem {
    return new PageContentPoem().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentPoem | PlainMessage<PageContentPoem> | undefined, b: PageContentPoem | PlainMessage<PageContentPoem> | undefined): boolean {
    return proto3.util.equals(PageContentPoem, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentHorizontalLine
 */
export class PageContentHorizontalLine extends Message<PageContentHorizontalLine> {
  constructor(data?: PartialMessage<PageContentHorizontalLine>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentHorizontalLine";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentHorizontalLine {
    return new PageContentHorizontalLine().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentHorizontalLine {
    return new PageContentHorizontalLine().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentHorizontalLine {
    return new PageContentHorizontalLine().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentHorizontalLine | PlainMessage<PageContentHorizontalLine> | undefined, b: PageContentHorizontalLine | PlainMessage<PageContentHorizontalLine> | undefined): boolean {
    return proto3.util.equals(PageContentHorizontalLine, a, b);
  }
}

/**
 * @generated from message ablibrary.types.PageContentReference
 */
export class PageContentReference extends Message<PageContentReference> {
  /**
   * @generated from field: ablibrary.types.PageContentReferenceKind kind = 1;
   */
  kind = PageContentReferenceKind.UNSPECIFIED;

  /**
   * @generated from field: string id = 2;
   */
  id = "";

  /**
   * @generated from field: string uri = 3;
   */
  uri = "";

  constructor(data?: PartialMessage<PageContentReference>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.PageContentReference";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "enum", T: proto3.getEnumType(PageContentReferenceKind) },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PageContentReference {
    return new PageContentReference().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PageContentReference {
    return new PageContentReference().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PageContentReference {
    return new PageContentReference().fromJsonString(jsonString, options);
  }

  static equals(a: PageContentReference | PlainMessage<PageContentReference> | undefined, b: PageContentReference | PlainMessage<PageContentReference> | undefined): boolean {
    return proto3.util.equals(PageContentReference, a, b);
  }
}

