// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/types/publisher.proto (package ablibrary.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Metadata } from "./metadata_pb";

/**
 * @generated from message ablibrary.types.Publisher
 */
export class Publisher extends Message<Publisher> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: optional string logo = 3;
   */
  logo?: string;

  /**
   * @generated from field: optional string bio = 4;
   */
  bio?: string;

  /**
   * @generated from field: optional ablibrary.types.Metadata metadata = 5;
   */
  metadata?: Metadata;

  constructor(data?: PartialMessage<Publisher>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.types.Publisher";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "logo", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "bio", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "metadata", kind: "message", T: Metadata, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Publisher {
    return new Publisher().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Publisher {
    return new Publisher().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Publisher {
    return new Publisher().fromJsonString(jsonString, options);
  }

  static equals(a: Publisher | PlainMessage<Publisher> | undefined, b: Publisher | PlainMessage<Publisher> | undefined): boolean {
    return proto3.util.equals(Publisher, a, b);
  }
}

