// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/types/tag.proto (package ablibrary.types, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Metadata } from "./metadata_pb";

/**
 * @generated from message ablibrary.types.Tag
 */
export declare class Tag extends Message<Tag> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 weight = 3;
   */
  weight: number;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional ablibrary.types.Metadata metadata = 5;
   */
  metadata?: Metadata;

  constructor(data?: PartialMessage<Tag>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.types.Tag";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tag;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tag;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tag;

  static equals(a: Tag | PlainMessage<Tag> | undefined, b: Tag | PlainMessage<Tag> | undefined): boolean;
}

/**
 * @generated from message ablibrary.types.TagTranslation
 */
export declare class TagTranslation extends Message<TagTranslation> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string tag_id = 2;
   */
  tagId: string;

  /**
   * @generated from field: string language_id = 3;
   */
  languageId: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: optional string description = 5;
   */
  description?: string;

  /**
   * @generated from field: optional ablibrary.types.Metadata metadata = 6;
   */
  metadata?: Metadata;

  constructor(data?: PartialMessage<TagTranslation>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.types.TagTranslation";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TagTranslation;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TagTranslation;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TagTranslation;

  static equals(a: TagTranslation | PlainMessage<TagTranslation> | undefined, b: TagTranslation | PlainMessage<TagTranslation> | undefined): boolean;
}

