// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/local_service/local_service.proto (package ablibrary.services.local_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckUpdatesRequest, CheckUpdatesResponse, EventBusRequest, EventBusResponse, GetInfoRequest, GetInfoResponse, ReloadRequest, ReloadResponse, ShutdownRequest, ShutdownResponse, SyncRequest, SyncResponse } from "./local_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.local_service.LocalService
 */
export const LocalService = {
  typeName: "ablibrary.services.local_service.LocalService",
  methods: {
    /**
     * @generated from rpc ablibrary.services.local_service.LocalService.GetInfo
     */
    getInfo: {
      name: "GetInfo",
      I: GetInfoRequest,
      O: GetInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.local_service.LocalService.EventBus
     */
    eventBus: {
      name: "EventBus",
      I: EventBusRequest,
      O: EventBusResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc ablibrary.services.local_service.LocalService.CheckUpdates
     */
    checkUpdates: {
      name: "CheckUpdates",
      I: CheckUpdatesRequest,
      O: CheckUpdatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.local_service.LocalService.Sync
     */
    sync: {
      name: "Sync",
      I: SyncRequest,
      O: SyncResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.local_service.LocalService.Shutdown
     */
    shutdown: {
      name: "Shutdown",
      I: ShutdownRequest,
      O: ShutdownResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.local_service.LocalService.Reload
     */
    reload: {
      name: "Reload",
      I: ReloadRequest,
      O: ReloadResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

