// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/category_service/category_service.proto (package ablibrary.services.category_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DetailsRequest, DetailsResponse, ListRequest, ListResponse } from "./category_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.category_service.CategoryService
 */
export const CategoryService = {
  typeName: "ablibrary.services.category_service.CategoryService",
  methods: {
    /**
     * @generated from rpc ablibrary.services.category_service.CategoryService.List
     */
    list: {
      name: "List",
      I: ListRequest,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.category_service.CategoryService.Details
     */
    details: {
      name: "Details",
      I: DetailsRequest,
      O: DetailsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

