// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/category_service/category_service.proto (package ablibrary.services.category_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { FieldMask } from "../../types/field_mask_pb";
import type { Category } from "../../types/category_pb";

/**
 * @generated from message ablibrary.services.category_service.ListRequest
 */
export declare class ListRequest extends Message<ListRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  constructor(data?: PartialMessage<ListRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.category_service.ListRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest;

  static equals(a: ListRequest | PlainMessage<ListRequest> | undefined, b: ListRequest | PlainMessage<ListRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.category_service.ListResponse
 */
export declare class ListResponse extends Message<ListResponse> {
  /**
   * @generated from field: repeated ablibrary.types.Category categories = 1;
   */
  categories: Category[];

  constructor(data?: PartialMessage<ListResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.category_service.ListResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponse;

  static equals(a: ListResponse | PlainMessage<ListResponse> | undefined, b: ListResponse | PlainMessage<ListResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.category_service.DetailsRequest
 */
export declare class DetailsRequest extends Message<DetailsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  constructor(data?: PartialMessage<DetailsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.category_service.DetailsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsRequest;

  static equals(a: DetailsRequest | PlainMessage<DetailsRequest> | undefined, b: DetailsRequest | PlainMessage<DetailsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.category_service.DetailsResponse
 */
export declare class DetailsResponse extends Message<DetailsResponse> {
  /**
   * @generated from field: ablibrary.types.Category category = 1;
   */
  category?: Category;

  constructor(data?: PartialMessage<DetailsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.category_service.DetailsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsResponse;

  static equals(a: DetailsResponse | PlainMessage<DetailsResponse> | undefined, b: DetailsResponse | PlainMessage<DetailsResponse> | undefined): boolean;
}

