// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/storage_service/storage_service.proto (package ablibrary.services.storage_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { FieldMask } from "../../types/field_mask_pb";
import type { Timestamp } from "../../types/common_pb";

/**
 * @generated from message ablibrary.services.storage_service.StatusRequest
 */
export declare class StatusRequest extends Message<StatusRequest> {
  constructor(data?: PartialMessage<StatusRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.StatusRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatusRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatusRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatusRequest;

  static equals(a: StatusRequest | PlainMessage<StatusRequest> | undefined, b: StatusRequest | PlainMessage<StatusRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.StatusResponse
 */
export declare class StatusResponse extends Message<StatusResponse> {
  /**
   * @generated from field: ablibrary.services.storage_service.Status status = 1;
   */
  status?: Status;

  constructor(data?: PartialMessage<StatusResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.StatusResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatusResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatusResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatusResponse;

  static equals(a: StatusResponse | PlainMessage<StatusResponse> | undefined, b: StatusResponse | PlainMessage<StatusResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.AnalyzeRequest
 */
export declare class AnalyzeRequest extends Message<AnalyzeRequest> {
  /**
   * @generated from field: ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: int32 max_depth = 2;
   */
  maxDepth: number;

  constructor(data?: PartialMessage<AnalyzeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.AnalyzeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AnalyzeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AnalyzeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AnalyzeRequest;

  static equals(a: AnalyzeRequest | PlainMessage<AnalyzeRequest> | undefined, b: AnalyzeRequest | PlainMessage<AnalyzeRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.AnalyzeResponse
 */
export declare class AnalyzeResponse extends Message<AnalyzeResponse> {
  /**
   * @generated from field: ablibrary.services.storage_service.FileTree file_tree = 1;
   */
  fileTree?: FileTree;

  constructor(data?: PartialMessage<AnalyzeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.AnalyzeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AnalyzeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AnalyzeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AnalyzeResponse;

  static equals(a: AnalyzeResponse | PlainMessage<AnalyzeResponse> | undefined, b: AnalyzeResponse | PlainMessage<AnalyzeResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.DeleteBookRequest
 */
export declare class DeleteBookRequest extends Message<DeleteBookRequest> {
  /**
   * @generated from field: repeated string book_ids = 1;
   */
  bookIds: string[];

  constructor(data?: PartialMessage<DeleteBookRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.DeleteBookRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteBookRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteBookRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteBookRequest;

  static equals(a: DeleteBookRequest | PlainMessage<DeleteBookRequest> | undefined, b: DeleteBookRequest | PlainMessage<DeleteBookRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.DeleteBookResponse
 */
export declare class DeleteBookResponse extends Message<DeleteBookResponse> {
  constructor(data?: PartialMessage<DeleteBookResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.DeleteBookResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteBookResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteBookResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteBookResponse;

  static equals(a: DeleteBookResponse | PlainMessage<DeleteBookResponse> | undefined, b: DeleteBookResponse | PlainMessage<DeleteBookResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.DeleteAllBooksRequest
 */
export declare class DeleteAllBooksRequest extends Message<DeleteAllBooksRequest> {
  constructor(data?: PartialMessage<DeleteAllBooksRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.DeleteAllBooksRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAllBooksRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAllBooksRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAllBooksRequest;

  static equals(a: DeleteAllBooksRequest | PlainMessage<DeleteAllBooksRequest> | undefined, b: DeleteAllBooksRequest | PlainMessage<DeleteAllBooksRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.DeleteAllBooksResponse
 */
export declare class DeleteAllBooksResponse extends Message<DeleteAllBooksResponse> {
  constructor(data?: PartialMessage<DeleteAllBooksResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.DeleteAllBooksResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAllBooksResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAllBooksResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAllBooksResponse;

  static equals(a: DeleteAllBooksResponse | PlainMessage<DeleteAllBooksResponse> | undefined, b: DeleteAllBooksResponse | PlainMessage<DeleteAllBooksResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.DeleteByPathRequest
 */
export declare class DeleteByPathRequest extends Message<DeleteByPathRequest> {
  /**
   * @generated from field: repeated string paths = 1;
   */
  paths: string[];

  constructor(data?: PartialMessage<DeleteByPathRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.DeleteByPathRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteByPathRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteByPathRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteByPathRequest;

  static equals(a: DeleteByPathRequest | PlainMessage<DeleteByPathRequest> | undefined, b: DeleteByPathRequest | PlainMessage<DeleteByPathRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.DeleteByPathResponse
 */
export declare class DeleteByPathResponse extends Message<DeleteByPathResponse> {
  constructor(data?: PartialMessage<DeleteByPathResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.DeleteByPathResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteByPathResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteByPathResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteByPathResponse;

  static equals(a: DeleteByPathResponse | PlainMessage<DeleteByPathResponse> | undefined, b: DeleteByPathResponse | PlainMessage<DeleteByPathResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.ClearTempRequest
 */
export declare class ClearTempRequest extends Message<ClearTempRequest> {
  constructor(data?: PartialMessage<ClearTempRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.ClearTempRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClearTempRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClearTempRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClearTempRequest;

  static equals(a: ClearTempRequest | PlainMessage<ClearTempRequest> | undefined, b: ClearTempRequest | PlainMessage<ClearTempRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.ClearTempResponse
 */
export declare class ClearTempResponse extends Message<ClearTempResponse> {
  constructor(data?: PartialMessage<ClearTempResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.ClearTempResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClearTempResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClearTempResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClearTempResponse;

  static equals(a: ClearTempResponse | PlainMessage<ClearTempResponse> | undefined, b: ClearTempResponse | PlainMessage<ClearTempResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.ClearStorageRequest
 */
export declare class ClearStorageRequest extends Message<ClearStorageRequest> {
  constructor(data?: PartialMessage<ClearStorageRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.ClearStorageRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClearStorageRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClearStorageRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClearStorageRequest;

  static equals(a: ClearStorageRequest | PlainMessage<ClearStorageRequest> | undefined, b: ClearStorageRequest | PlainMessage<ClearStorageRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.ClearStorageResponse
 */
export declare class ClearStorageResponse extends Message<ClearStorageResponse> {
  constructor(data?: PartialMessage<ClearStorageResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.ClearStorageResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClearStorageResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClearStorageResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClearStorageResponse;

  static equals(a: ClearStorageResponse | PlainMessage<ClearStorageResponse> | undefined, b: ClearStorageResponse | PlainMessage<ClearStorageResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.GetSettingsRequest
 */
export declare class GetSettingsRequest extends Message<GetSettingsRequest> {
  constructor(data?: PartialMessage<GetSettingsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.GetSettingsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSettingsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSettingsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSettingsRequest;

  static equals(a: GetSettingsRequest | PlainMessage<GetSettingsRequest> | undefined, b: GetSettingsRequest | PlainMessage<GetSettingsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.GetSettingsResponse
 */
export declare class GetSettingsResponse extends Message<GetSettingsResponse> {
  /**
   * @generated from field: ablibrary.services.storage_service.Settings settings = 1;
   */
  settings?: Settings;

  constructor(data?: PartialMessage<GetSettingsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.GetSettingsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSettingsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSettingsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSettingsResponse;

  static equals(a: GetSettingsResponse | PlainMessage<GetSettingsResponse> | undefined, b: GetSettingsResponse | PlainMessage<GetSettingsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.SetSettingsRequest
 */
export declare class SetSettingsRequest extends Message<SetSettingsRequest> {
  /**
   * @generated from field: ablibrary.services.storage_service.Settings settings = 1;
   */
  settings?: Settings;

  constructor(data?: PartialMessage<SetSettingsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.SetSettingsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSettingsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSettingsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSettingsRequest;

  static equals(a: SetSettingsRequest | PlainMessage<SetSettingsRequest> | undefined, b: SetSettingsRequest | PlainMessage<SetSettingsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.SetSettingsResponse
 */
export declare class SetSettingsResponse extends Message<SetSettingsResponse> {
  constructor(data?: PartialMessage<SetSettingsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.SetSettingsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetSettingsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetSettingsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetSettingsResponse;

  static equals(a: SetSettingsResponse | PlainMessage<SetSettingsResponse> | undefined, b: SetSettingsResponse | PlainMessage<SetSettingsResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.Status
 */
export declare class Status extends Message<Status> {
  /**
   * @generated from field: ablibrary.services.storage_service.Status.Location location = 1;
   */
  location?: Status_Location;

  /**
   * @generated from field: ablibrary.services.storage_service.Status.Books books = 2;
   */
  books?: Status_Books;

  /**
   * @generated from field: int64 temp_bytes_total = 3;
   */
  tempBytesTotal: bigint;

  /**
   * @generated from field: int64 bytes_total = 4;
   */
  bytesTotal: bigint;

  constructor(data?: PartialMessage<Status>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.Status";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Status;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Status;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Status;

  static equals(a: Status | PlainMessage<Status> | undefined, b: Status | PlainMessage<Status> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.Status.DirInfo
 */
export declare class Status_DirInfo extends Message<Status_DirInfo> {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: int32 count = 2;
   */
  count: number;

  /**
   * @generated from field: int64 bytes_total = 3;
   */
  bytesTotal: bigint;

  constructor(data?: PartialMessage<Status_DirInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.Status.DirInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Status_DirInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Status_DirInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Status_DirInfo;

  static equals(a: Status_DirInfo | PlainMessage<Status_DirInfo> | undefined, b: Status_DirInfo | PlainMessage<Status_DirInfo> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.Status.Location
 */
export declare class Status_Location extends Message<Status_Location> {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: int64 bytes_total = 2;
   */
  bytesTotal: bigint;

  /**
   * @generated from field: int64 bytes_free = 3;
   */
  bytesFree: bigint;

  constructor(data?: PartialMessage<Status_Location>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.Status.Location";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Status_Location;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Status_Location;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Status_Location;

  static equals(a: Status_Location | PlainMessage<Status_Location> | undefined, b: Status_Location | PlainMessage<Status_Location> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.Status.Books
 */
export declare class Status_Books extends Message<Status_Books> {
  /**
   * @generated from field: int32 count = 1;
   */
  count: number;

  /**
   * @generated from field: int64 bytes_total = 2;
   */
  bytesTotal: bigint;

  /**
   * @generated from field: map<string, ablibrary.services.storage_service.Status.Books.Item> items = 3;
   */
  items: { [key: string]: Status_Books_Item };

  constructor(data?: PartialMessage<Status_Books>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.Status.Books";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Status_Books;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Status_Books;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Status_Books;

  static equals(a: Status_Books | PlainMessage<Status_Books> | undefined, b: Status_Books | PlainMessage<Status_Books> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.Status.Books.Item
 */
export declare class Status_Books_Item extends Message<Status_Books_Item> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: optional string hash = 3;
   */
  hash?: string;

  /**
   * @generated from field: int64 size_bytes = 4;
   */
  sizeBytes: bigint;

  constructor(data?: PartialMessage<Status_Books_Item>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.Status.Books.Item";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Status_Books_Item;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Status_Books_Item;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Status_Books_Item;

  static equals(a: Status_Books_Item | PlainMessage<Status_Books_Item> | undefined, b: Status_Books_Item | PlainMessage<Status_Books_Item> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.Settings
 */
export declare class Settings extends Message<Settings> {
  /**
   * @generated from field: string storage_path = 1;
   */
  storagePath: string;

  /**
   * @generated from field: int32 auto_delete_temp_after_days = 2;
   */
  autoDeleteTempAfterDays: number;

  /**
   * @generated from field: int64 storage_size_warning_threshold = 3;
   */
  storageSizeWarningThreshold: bigint;

  constructor(data?: PartialMessage<Settings>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.Settings";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Settings;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Settings;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Settings;

  static equals(a: Settings | PlainMessage<Settings> | undefined, b: Settings | PlainMessage<Settings> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.storage_service.FileTree
 */
export declare class FileTree extends Message<FileTree> {
  /**
   * The base name of the file or directory.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The full path of the file or directory.
   *
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * The kind of the file or directory.
   *
   * @generated from field: ablibrary.services.storage_service.FileTree.Kind kind = 3;
   */
  kind: FileTree_Kind;

  /**
   * @generated from field: int64 size_bytes = 4;
   */
  sizeBytes: bigint;

  /**
   * @generated from field: ablibrary.types.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: ablibrary.types.Timestamp modified_at = 6;
   */
  modifiedAt?: Timestamp;

  /**
   * @generated from field: ablibrary.types.Timestamp last_accessed_at = 7;
   */
  lastAccessedAt?: Timestamp;

  /**
   * @generated from field: repeated ablibrary.services.storage_service.FileTree children = 8;
   */
  children: FileTree[];

  constructor(data?: PartialMessage<FileTree>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.storage_service.FileTree";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FileTree;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FileTree;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FileTree;

  static equals(a: FileTree | PlainMessage<FileTree> | undefined, b: FileTree | PlainMessage<FileTree> | undefined): boolean;
}

/**
 * @generated from enum ablibrary.services.storage_service.FileTree.Kind
 */
export declare enum FileTree_Kind {
  /**
   * @generated from enum value: KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: KIND_FILE = 1;
   */
  FILE = 1,

  /**
   * @generated from enum value: KIND_DIRECTORY = 2;
   */
  DIRECTORY = 2,

  /**
   * @generated from enum value: KIND_SYMLINK = 3;
   */
  SYMLINK = 3,
}

