// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/publisher_service/publisher_service.proto (package ablibrary.services.publisher_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { FieldMask } from "../../types/field_mask_pb";
import type { SortDirection } from "../../types/common_pb";
import type { Publisher } from "../../types/publisher_pb";
import type { Pagination } from "../../types/pagination_pb";

/**
 * @generated from message ablibrary.services.publisher_service.ListRequest
 */
export declare class ListRequest extends Message<ListRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: optional int32 page = 2;
   */
  page?: number;

  /**
   * @generated from field: optional int32 per_page = 3;
   */
  perPage?: number;

  /**
   * @generated from field: optional string query = 4;
   */
  query?: string;

  /**
   * @generated from field: optional ablibrary.services.publisher_service.ListRequest.PublisherSort sort_by = 5;
   */
  sortBy?: ListRequest_PublisherSort;

  /**
   * @generated from field: optional ablibrary.types.SortDirection sort_dir = 6;
   */
  sortDir?: SortDirection;

  /**
   * @generated from field: repeated ablibrary.services.publisher_service.ListRequest.BookFilter books = 7;
   */
  books: ListRequest_BookFilter[];

  /**
   * @generated from field: repeated ablibrary.services.publisher_service.ListRequest.PublisherFilter publishers = 8;
   */
  publishers: ListRequest_PublisherFilter[];

  /**
   * @generated from field: repeated ablibrary.services.publisher_service.ListRequest.TagFilter tags = 9;
   */
  tags: ListRequest_TagFilter[];

  constructor(data?: PartialMessage<ListRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest;

  static equals(a: ListRequest | PlainMessage<ListRequest> | undefined, b: ListRequest | PlainMessage<ListRequest> | undefined): boolean;
}

/**
 * @generated from enum ablibrary.services.publisher_service.ListRequest.PublisherSort
 */
export declare enum ListRequest_PublisherSort {
  /**
   * @generated from enum value: PUBLISHER_SORT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PUBLISHER_SORT_NAME = 1;
   */
  NAME = 1,

  /**
   * @generated from enum value: PUBLISHER_SORT_DIED_AT = 2;
   */
  DIED_AT = 2,

  /**
   * @generated from enum value: PUBLISHER_SORT_BOOK_COUNT = 3;
   */
  BOOK_COUNT = 3,

  /**
   * @generated from enum value: PUBLISHER_SORT_BORN_AT = 4;
   */
  BORN_AT = 4,

  /**
   * @generated from enum value: PUBLISHER_SORT_ERA = 5;
   */
  ERA = 5,

  /**
   * @generated from enum value: PUBLISHER_SORT_CREATED_AT = 6;
   */
  CREATED_AT = 6,

  /**
   * @generated from enum value: PUBLISHER_SORT_UPDATED_AT = 7;
   */
  UPDATED_AT = 7,
}

/**
 * @generated from message ablibrary.services.publisher_service.ListRequest.BookFilter
 */
export declare class ListRequest_BookFilter extends Message<ListRequest_BookFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string title = 2;
   */
  title?: string;

  /**
   * @generated from field: repeated string roles = 3;
   */
  roles: string[];

  constructor(data?: PartialMessage<ListRequest_BookFilter>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListRequest.BookFilter";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_BookFilter;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_BookFilter;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_BookFilter;

  static equals(a: ListRequest_BookFilter | PlainMessage<ListRequest_BookFilter> | undefined, b: ListRequest_BookFilter | PlainMessage<ListRequest_BookFilter> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.publisher_service.ListRequest.PublisherFilter
 */
export declare class ListRequest_PublisherFilter extends Message<ListRequest_PublisherFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  constructor(data?: PartialMessage<ListRequest_PublisherFilter>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListRequest.PublisherFilter";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_PublisherFilter;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_PublisherFilter;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_PublisherFilter;

  static equals(a: ListRequest_PublisherFilter | PlainMessage<ListRequest_PublisherFilter> | undefined, b: ListRequest_PublisherFilter | PlainMessage<ListRequest_PublisherFilter> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.publisher_service.ListRequest.TagFilter
 */
export declare class ListRequest_TagFilter extends Message<ListRequest_TagFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  constructor(data?: PartialMessage<ListRequest_TagFilter>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListRequest.TagFilter";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_TagFilter;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_TagFilter;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_TagFilter;

  static equals(a: ListRequest_TagFilter | PlainMessage<ListRequest_TagFilter> | undefined, b: ListRequest_TagFilter | PlainMessage<ListRequest_TagFilter> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.publisher_service.ListResponse
 */
export declare class ListResponse extends Message<ListResponse> {
  /**
   * @generated from field: repeated ablibrary.types.Publisher publishers = 1;
   */
  publishers: Publisher[];

  /**
   * @generated from field: ablibrary.types.Pagination pagination = 2;
   */
  pagination?: Pagination;

  constructor(data?: PartialMessage<ListResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponse;

  static equals(a: ListResponse | PlainMessage<ListResponse> | undefined, b: ListResponse | PlainMessage<ListResponse> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.publisher_service.DetailsRequest
 */
export declare class DetailsRequest extends Message<DetailsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  constructor(data?: PartialMessage<DetailsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.publisher_service.DetailsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsRequest;

  static equals(a: DetailsRequest | PlainMessage<DetailsRequest> | undefined, b: DetailsRequest | PlainMessage<DetailsRequest> | undefined): boolean;
}

/**
 * @generated from message ablibrary.services.publisher_service.DetailsResponse
 */
export declare class DetailsResponse extends Message<DetailsResponse> {
  /**
   * @generated from field: ablibrary.types.Publisher publisher = 1;
   */
  publisher?: Publisher;

  constructor(data?: PartialMessage<DetailsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ablibrary.services.publisher_service.DetailsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsResponse;

  static equals(a: DetailsResponse | PlainMessage<DetailsResponse> | undefined, b: DetailsResponse | PlainMessage<DetailsResponse> | undefined): boolean;
}

