// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/publisher_service/publisher_service.proto (package ablibrary.services.publisher_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DetailsRequest, DetailsResponse, ListRequest, ListResponse } from "./publisher_service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ablibrary.services.publisher_service.PublisherService
 */
export const PublisherService = {
  typeName: "ablibrary.services.publisher_service.PublisherService",
  methods: {
    /**
     * @generated from rpc ablibrary.services.publisher_service.PublisherService.List
     */
    list: {
      name: "List",
      I: ListRequest,
      O: ListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ablibrary.services.publisher_service.PublisherService.Details
     */
    details: {
      name: "Details",
      I: DetailsRequest,
      O: DetailsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

