// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+dts,import_extension=none"
// @generated from file ablibrary/services/publisher_service/publisher_service.proto (package ablibrary.services.publisher_service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { FieldMask } from "../../types/field_mask_pb";
import { SortDirection } from "../../types/common_pb";
import { Publisher } from "../../types/publisher_pb";
import { Pagination } from "../../types/pagination_pb";

/**
 * @generated from message ablibrary.services.publisher_service.ListRequest
 */
export class ListRequest extends Message<ListRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: optional int32 page = 2;
   */
  page?: number;

  /**
   * @generated from field: optional int32 per_page = 3;
   */
  perPage?: number;

  /**
   * @generated from field: optional string query = 4;
   */
  query?: string;

  /**
   * @generated from field: optional ablibrary.services.publisher_service.ListRequest.PublisherSort sort_by = 5;
   */
  sortBy?: ListRequest_PublisherSort;

  /**
   * @generated from field: optional ablibrary.types.SortDirection sort_dir = 6;
   */
  sortDir?: SortDirection;

  /**
   * @generated from field: repeated ablibrary.services.publisher_service.ListRequest.BookFilter books = 7;
   */
  books: ListRequest_BookFilter[] = [];

  /**
   * @generated from field: repeated ablibrary.services.publisher_service.ListRequest.PublisherFilter publishers = 8;
   */
  publishers: ListRequest_PublisherFilter[] = [];

  /**
   * @generated from field: repeated ablibrary.services.publisher_service.ListRequest.TagFilter tags = 9;
   */
  tags: ListRequest_TagFilter[] = [];

  constructor(data?: PartialMessage<ListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mask", kind: "message", T: FieldMask, opt: true },
    { no: 2, name: "page", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 3, name: "per_page", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 4, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "sort_by", kind: "enum", T: proto3.getEnumType(ListRequest_PublisherSort), opt: true },
    { no: 6, name: "sort_dir", kind: "enum", T: proto3.getEnumType(SortDirection), opt: true },
    { no: 7, name: "books", kind: "message", T: ListRequest_BookFilter, repeated: true },
    { no: 8, name: "publishers", kind: "message", T: ListRequest_PublisherFilter, repeated: true },
    { no: 9, name: "tags", kind: "message", T: ListRequest_TagFilter, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest {
    return new ListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest {
    return new ListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest {
    return new ListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest | PlainMessage<ListRequest> | undefined, b: ListRequest | PlainMessage<ListRequest> | undefined): boolean {
    return proto3.util.equals(ListRequest, a, b);
  }
}

/**
 * @generated from enum ablibrary.services.publisher_service.ListRequest.PublisherSort
 */
export enum ListRequest_PublisherSort {
  /**
   * @generated from enum value: PUBLISHER_SORT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PUBLISHER_SORT_NAME = 1;
   */
  NAME = 1,

  /**
   * @generated from enum value: PUBLISHER_SORT_DIED_AT = 2;
   */
  DIED_AT = 2,

  /**
   * @generated from enum value: PUBLISHER_SORT_BOOK_COUNT = 3;
   */
  BOOK_COUNT = 3,

  /**
   * @generated from enum value: PUBLISHER_SORT_BORN_AT = 4;
   */
  BORN_AT = 4,

  /**
   * @generated from enum value: PUBLISHER_SORT_ERA = 5;
   */
  ERA = 5,

  /**
   * @generated from enum value: PUBLISHER_SORT_CREATED_AT = 6;
   */
  CREATED_AT = 6,

  /**
   * @generated from enum value: PUBLISHER_SORT_UPDATED_AT = 7;
   */
  UPDATED_AT = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(ListRequest_PublisherSort)
proto3.util.setEnumType(ListRequest_PublisherSort, "ablibrary.services.publisher_service.ListRequest.PublisherSort", [
  { no: 0, name: "PUBLISHER_SORT_UNSPECIFIED" },
  { no: 1, name: "PUBLISHER_SORT_NAME" },
  { no: 2, name: "PUBLISHER_SORT_DIED_AT" },
  { no: 3, name: "PUBLISHER_SORT_BOOK_COUNT" },
  { no: 4, name: "PUBLISHER_SORT_BORN_AT" },
  { no: 5, name: "PUBLISHER_SORT_ERA" },
  { no: 6, name: "PUBLISHER_SORT_CREATED_AT" },
  { no: 7, name: "PUBLISHER_SORT_UPDATED_AT" },
]);

/**
 * @generated from message ablibrary.services.publisher_service.ListRequest.BookFilter
 */
export class ListRequest_BookFilter extends Message<ListRequest_BookFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string title = 2;
   */
  title?: string;

  /**
   * @generated from field: repeated string roles = 3;
   */
  roles: string[] = [];

  constructor(data?: PartialMessage<ListRequest_BookFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListRequest.BookFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "roles", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_BookFilter {
    return new ListRequest_BookFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_BookFilter {
    return new ListRequest_BookFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_BookFilter {
    return new ListRequest_BookFilter().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest_BookFilter | PlainMessage<ListRequest_BookFilter> | undefined, b: ListRequest_BookFilter | PlainMessage<ListRequest_BookFilter> | undefined): boolean {
    return proto3.util.equals(ListRequest_BookFilter, a, b);
  }
}

/**
 * @generated from message ablibrary.services.publisher_service.ListRequest.PublisherFilter
 */
export class ListRequest_PublisherFilter extends Message<ListRequest_PublisherFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  constructor(data?: PartialMessage<ListRequest_PublisherFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListRequest.PublisherFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_PublisherFilter {
    return new ListRequest_PublisherFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_PublisherFilter {
    return new ListRequest_PublisherFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_PublisherFilter {
    return new ListRequest_PublisherFilter().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest_PublisherFilter | PlainMessage<ListRequest_PublisherFilter> | undefined, b: ListRequest_PublisherFilter | PlainMessage<ListRequest_PublisherFilter> | undefined): boolean {
    return proto3.util.equals(ListRequest_PublisherFilter, a, b);
  }
}

/**
 * @generated from message ablibrary.services.publisher_service.ListRequest.TagFilter
 */
export class ListRequest_TagFilter extends Message<ListRequest_TagFilter> {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  constructor(data?: PartialMessage<ListRequest_TagFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListRequest.TagFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRequest_TagFilter {
    return new ListRequest_TagFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRequest_TagFilter {
    return new ListRequest_TagFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRequest_TagFilter {
    return new ListRequest_TagFilter().fromJsonString(jsonString, options);
  }

  static equals(a: ListRequest_TagFilter | PlainMessage<ListRequest_TagFilter> | undefined, b: ListRequest_TagFilter | PlainMessage<ListRequest_TagFilter> | undefined): boolean {
    return proto3.util.equals(ListRequest_TagFilter, a, b);
  }
}

/**
 * @generated from message ablibrary.services.publisher_service.ListResponse
 */
export class ListResponse extends Message<ListResponse> {
  /**
   * @generated from field: repeated ablibrary.types.Publisher publishers = 1;
   */
  publishers: Publisher[] = [];

  /**
   * @generated from field: ablibrary.types.Pagination pagination = 2;
   */
  pagination?: Pagination;

  constructor(data?: PartialMessage<ListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.publisher_service.ListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "publishers", kind: "message", T: Publisher, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: Pagination },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponse {
    return new ListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponse {
    return new ListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponse {
    return new ListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListResponse | PlainMessage<ListResponse> | undefined, b: ListResponse | PlainMessage<ListResponse> | undefined): boolean {
    return proto3.util.equals(ListResponse, a, b);
  }
}

/**
 * @generated from message ablibrary.services.publisher_service.DetailsRequest
 */
export class DetailsRequest extends Message<DetailsRequest> {
  /**
   * @generated from field: optional ablibrary.types.FieldMask mask = 1;
   */
  mask?: FieldMask;

  /**
   * @generated from field: string id = 2;
   */
  id = "";

  constructor(data?: PartialMessage<DetailsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.publisher_service.DetailsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "mask", kind: "message", T: FieldMask, opt: true },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsRequest {
    return new DetailsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsRequest {
    return new DetailsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsRequest {
    return new DetailsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DetailsRequest | PlainMessage<DetailsRequest> | undefined, b: DetailsRequest | PlainMessage<DetailsRequest> | undefined): boolean {
    return proto3.util.equals(DetailsRequest, a, b);
  }
}

/**
 * @generated from message ablibrary.services.publisher_service.DetailsResponse
 */
export class DetailsResponse extends Message<DetailsResponse> {
  /**
   * @generated from field: ablibrary.types.Publisher publisher = 1;
   */
  publisher?: Publisher;

  constructor(data?: PartialMessage<DetailsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ablibrary.services.publisher_service.DetailsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "publisher", kind: "message", T: Publisher },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DetailsResponse {
    return new DetailsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DetailsResponse {
    return new DetailsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DetailsResponse {
    return new DetailsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DetailsResponse | PlainMessage<DetailsResponse> | undefined, b: DetailsResponse | PlainMessage<DetailsResponse> | undefined): boolean {
    return proto3.util.equals(DetailsResponse, a, b);
  }
}

